### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by yalokin** [castwide/vscode-solargraph#1]
I have ubuntu 16.04, rvm, ruby 2.4, VS Code 1.10.2. I installed gem and extension, but it does not work

**Comment by castwide** [comment]
Thanks for the report. I found a bug in installation code that runs the first time the library gets used. I updated the gem to version 0.2.2. Please try updating on your system and let me know if it fixes the problem.

**Comment by yalokin** [comment]
It worked! Thanks!
