### ISSUE TITLE
Issue with installing the gem

### ISSUE THREAD

**Issue by AlminCode** [castwide/vscode-solargraph#10]
Hello, 

So I've come across an issue with 0.11.1 version of the gem, where I install the gem thru the console however when opening VS code I get the following: 

![image](https://user-images.githubusercontent.com/6343910/30016324-ebc8fc8e-9154-11e7-9e64-65d494654d2c.png)
![image](https://user-images.githubusercontent.com/6343910/30016330-eebdb808-9154-11e7-89ac-e994e67644bf.png)

My console shows me it is installed however VS code does not. I've tried rebooting, restarting VS Code etc. however that does not seem to fix my issue. 

Now one possible solution or issue that I have is that my ruby code is NOT executed on my machine, but the code is being synced to a remote server. I do not run the code, so the gemfile is never executed, maybe this causes the issue ? (I'm fairly new to ruby, sorry If I'm missing something)

**Comment by castwide** [comment]
You need to have Ruby and the Solargraph gem installed on the machine where VS Code is running. The extension uses a background process to analyze the code and provide suggestions through a web API.

The code you're editing doesn't need to be executed on your local machine. Solargraph only needs to read the files. But if you want code completion for any other gems you use, they also need to be installed locally.

**Comment by AlminCode** [comment]
@castwide Hey, thanks for the answer, I did all that.

Well, I added it into my Gemfile and then installed all the gems. However, again it has thrown the same error when starting VSCode. I also manually started the server and it did not work, I will later try on a fresh installation of VSCode and take a better look at the console. 

Something offtopic maybe: http://solargraph.org/demo when I visit the demo site it seems not to be working, Im on MacOS using Chrome, no console errors.

**Comment by AlminCode** [comment]
@castwide Ok, I've created an empty ruby file and it works. 

Now what could be the issue is that my project is very big with lots of .rb files. I will try to tweak the .yml file to see if that causes my issue. 

Anyway, sorry for bothering you and thanks! The issue is on my side, once I find the solution I will update if needed.

**Comment by castwide** [comment]
No problem, @AlminCode. Glad you got it working. Please let me know if you run into other problems or anything.

Regarding the demo: it only provides completion items if you hit ctrl+space. There's also a bug in completing literal values (see https://github.com/castwide/solargraph/issues/7). That should be fixed in 0.11.2, which I plan to release in the next couple days. If there are other issues you're having, please feel free to report them.

**Comment by stevenyepes** [comment]
I have the same problem, when I open a rb file it doesn't provides autocomplete :(, maybe is something related to my ruby installation? do I need something more than just Ruby and solargraph?

**Comment by castwide** [comment]
The vscode-ruby extension, Ruby installed on the same machine, and the Solargraph gem should be all you need. Opening a .rb file should activate the extension. It might take a few seconds for the server to start.

Some questions that might help me troubleshoot your issue:

1. Can you give me an example of code that doesn't trigger autocompletions? This should be sufficient to get Array method suggestions:

    [].

2. Do you have a workspace (folder) open? If so, the size of the project might be an issue. Also, see #9 for a known bug regarding test folders.

3. If you toggle the developer tools on, does the console show any errors?

**Comment by stevenyepes** [comment]
Thanks for the answer, this is the code, I just create a simple class to try but nothing happend, I open the complete folder of the project but it has just one file. I'll going to check that bug.

The developers tools are clean.

`class Ventilador
    def initialize(params)
        @marca = params[:marca]
        @velocidad = params[:velocidad]
    end
    def presentacion
        "La marca del ventilador es: #{@marca}"
    end

    def cambiarVelocidad()
        if @velocidad > 50
            @velocidad = 0
        else
            @velocidad = @velocidad + 10
        end
    end

    def marca
        @marca
    end
end

objeto_ventilador = Ventilador.new({marca: 'XYZ', velocidad: 10})
10.times {
    puts "La velocidad cambió a: #{objeto_ventilador.cambiarVelocidad}"
}

`

**Comment by castwide** [comment]
I copied your code into a test.rb file in an otherwise empty folder and opened it in VS Code. Starting a new line with `obj` returned the expected suggestions, including `objeto_ventilador`. Typing `objeto_ventilador.` returned `Ventilador` instance methods, including `cambiarVelocidad` at the top of the list. Do either of those work for you? If so, what doesn't?

A few other questions:

* What operating system are you using?
* What version of Ruby?
* What version of the vscode-solargraph extension?
* Do you have any other extensions installed?
* What version of the Solargraph gem? (Run `gem list solargraph`)
* Does running `solargraph help` return a list of commands?
* Did you change any of the Solargraph configuration settings?

You might also want to check File -> Preferences -> Settings to make sure suggestions aren't disabled. Search "suggestion" for relevant options. But even if they're disabled, ctrl+space should still bring them up.

Thanks for your patience in troubleshooting this with me.

**Comment by stevenyepes** [comment]
- I'm using Windows 7 Ultimate
- Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
- Ruby solargraph in vscode 0.7.1
- solargraph (0.11.2)
- These are all my extensions in vscode:
`λ code --list-extensions
castwide.solargraph
donjayamanne.python
eg2.tslint
formulahendry.terminal
johnpapa.Angular2
justusadam.language-haskell
lukehoban.Go
Mikael.Angular-BeastCode
ms-vscode.atom-keybindings
PeterJausovec.vscode-docker
rbbit.typescript-hero
thekalinga.bootstrap4-vscode
tht13.html-preview-vscode
tht13.python
UCL.haskelly`
- Yes, it returns all the comands
- I just installed the extension and didn't touch anything else

Suggestions are enabled : `  "editor.quickSuggestions": {
    "other": true,
    "comments": false,
    "strings": false
  },
`
Thanks for your help.

**Comment by castwide** [comment]
Nothing there looks unusual. I tried installing the same extensions and still got the expected autocompletions. Windows 7 and 2.4.1 shouldn't be a problem, but I'll try to duplicate that environment if all else fails.

One other thing we can try: make sure the server is accessible.

* Run `solargraph server -p 0`
* You should get output something like this (the port number will vary):
    [2017-09-08 22:55:16] INFO  WEBrick 1.3.1
    [2017-09-08 22:55:16] INFO  ruby 2.3.3 (2016-11-21) [x64-mingw32]
    == Sinatra (v2.0.0) has taken the stage on 0 for development with backup from WEBrick
    [2017-09-08 22:55:16] INFO  WEBrick::HTTPServer#start: pid=280496 **port=63209**
* Try browsing to the specified port on localhost, e.g., http://localhost:63209
* You should get a page that says "Sinatra doesn't know this ditty." (It's an error message, but it verifies that the server is responding to requests.)

**Comment by stevenyepes** [comment]
![imagen](https://user-images.githubusercontent.com/8420884/30236574-1013c34a-94e2-11e7-963b-b9b6605d6cc8.png)

solargraph is running normally 

Aditionally when I run  (Ctrl + Shift + R) for documentation I got this:
![imagen](https://user-images.githubusercontent.com/8420884/30236602-66375278-94e2-11e7-8fc9-049848dd009b.png)

**Comment by castwide** [comment]
You might have pinpointed the issue. Try running `gem install bundler` and reopening VS Code.

**Comment by stevenyepes** [comment]
Awesome, everything is working now!

I really appreciate your help.

**Comment by castwide** [comment]
Great! Thanks for working through it with me.

In the next version of the gem I'll either add a dependency to bundler or make it optional in the library.

**Comment by castwide** [comment]
Gem version 0.12.0 eliminates the bundler requirement.

**Comment by kissu** [comment]
I'd like to share my **working** configuration if somebody ever need it one day:
```diff
"ruby.useBundler": true,
+  "ruby.intellisense": "rubyLocate",
  "ruby.lintDebounceTime": 300,
  "ruby.lint": {
    "ruby": {
      "unicode": true //Runs ruby -wc -Ku
    },
    "rubocop": {
      "lint": true,
      "rails": true
    },
  },
  "solargraph.diagnostics": true,
  "solargraph.autoformat": true,
  "solargraph.completion": true,
  "solargraph.useBundler": true,
  "solargraph.formatting": true,
```

I got some issues setting it up working all the time. Sometimes it does work but not after a restart, said `solargraph gem is not installed`...
Then I put `"ruby.intellisense": "rubyLocate"` and now, it's working like a charm. ❤️ 

May be useful for some people:
- `MacOS, 10.13.5`
- `gem solargraph, 0.22.0`
- `VScode solargraph, 0.17.4`
- `ruby, 2.5.1p57`
- `Rails, 5.2.0`

**Comment by AnwarShah** [comment]
I added rvm sourcing in `.bashrc` file and somehow that was causing the problem although I've installed solargraph and can run it through terminal. Moved it to `.profile` and solargraph is recognized by vscode!! What was going on there?
