### ISSUE TITLE
Solargraph gives no failure message when solargraph gem isn't installed

### ISSUE THREAD

**Issue by connorshea** [castwide/vscode-solargraph#100]
I'm not sure why this is/was happening, maybe because I upgraded to Ruby 2.6, or because of something else, but I had "Starting the Solargraph language server..." stuck in my VSCode bottom bar and nothing was happening. I was unaware of the problem for a week or two and just assumed the extension had an issue of some sort that'd be fixed in a few days.

I'm not sure if there's no "gem not found" error or if the extension was getting stuck somewhere and failed to warn me for some other reason, but it'd be nice if there was some sort of notification for this problem :)

Extension version: 0.19.1
VS Code version: Code 1.30.2 (61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8, 2019-01-07T22:48:31.260Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.28GB free)|
|Process Argv|-psn_0_1016056|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by castwide** [comment]
There should definitely be an indication from the extension when the gem isn't installed. I'll look into it.

**Comment by castwide** [comment]
Extension v0.19.2 reinstates the notification when the gem is not found.

**Comment by connorshea** [comment]
Thanks!
