### ISSUE TITLE
Jump to spec file?

### ISSUE THREAD

**Issue by edisonywh** [castwide/vscode-solargraph#102]
Not sure how common is this feature, but I see my friend's [plugin on Sublime](https://github.com/astrauka/TestRSpec) being able to jump to spec file of the current file (and prompts creation if it's not already created).

Just popped into my mind that this is probably a language server is able to do, but not sure the feasibility. Wonder if there's already a feature like this or if it is on the features roadmap? (or if someone could point me to a similar plugin)

**Comment by castwide** [comment]
There are no current plans to support this feature in vscode-solargraph. It's not part of the LSP specification, either.

There are a few other VS Code extensions that provide features along those lines. This one worked out of the box for me: https://marketplace.visualstudio.com/items?itemName=blakeh.jump-to-test

**Comment by edisonywh** [comment]
I see, thanks for the clarification!

And wow that worked well, thanks!

I was using [this](https://marketplace.visualstudio.com/items?itemName=Lourenci.go-to-spec) and it didn't work for me.
