### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by davidmeddina** [castwide/vscode-solargraph#109]
- Issue Type: `Performance`
- Extension Name: `solargraph`
- Extension Version: `0.19.6`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/david/castwide.solargraph-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by castwide** [comment]
Do you have the `castwide.solargraph-unresponsive.cpuprofile.txt` that the message asks you to attach?

**Comment by castwide** [comment]
An update the improves performance is being tracked in #117. Please feel free to comment there or open a new issue if you think your problem has a different root cause.
