### ISSUE TITLE
Go to definition opens peek

### ISSUE THREAD

**Issue by MicMicMon** [castwide/vscode-solargraph#114]
When I use "Go To Definition" on a class definition, it opens Peek because it finds 2 defintions of the class. But the two definitions actually are the same (located at the same line).

So the expected behavior is that it should find only one and go to definiton straight away.

Is there something I miss here? Example below:

![image](https://user-images.githubusercontent.com/37897072/57240400-a2952280-702e-11e9-8b6b-c33ff9b84c05.png)

**Comment by castwide** [comment]
I believe this was related to a bug in the gem that caused irregular map updates under some circumstances, especially when an external process changed the project's files. It should be fixed in gem version 0.32.2, which was released today. If you still experience the problem, please let me know.

**Comment by MicMicMon** [comment]
Thanks for the response!
Ah damn, I updated to 0.32.2 but still experience the issue.
Is there any cache I should remove from the old version before trying again?

**Comment by castwide** [comment]
It shouldn't be a cache issue.

I haven't been able to reproduce the error. Here's a couple things that can help troubleshoot:

1. Can you confirm that both definitions go to the same line? It's possible that the second one points to a different location that reopens the IdOperator class.

2. Can you provide a minimal reproducible example?

**Comment by yyyy7** [comment]
I got the same issue.

**Comment by castwide** [comment]
I was finally able to reproduce it by having Go To Definition enabled in two extensions. In my case, it was vscode-solargraph and vscode-ruby. Setting `ruby.intellisense` to `false` fixes the issue.

If you'd rather use vscode-ruby's version, you can set `ruby.intellisense` to `rubyLocate` and `solargraph.definitions` to `false`.

**Comment by MicMicMon** [comment]
Thanks, great! Indeed, solves the issue for me.
So I close this issue.

Feel free to comment below if you still have trouble though of course!
