### ISSUE TITLE
command 'solargraph.buildGemDocs' not found (vs code)

### ISSUE THREAD

**Issue by jpmachado99** [castwide/vscode-solargraph#120]
I can't understand the cause of this error. I installed the gems correctly, following the repository doc.
In the end nothing of the extension works on my computer(autocomplete and inline doc). 
Using Windows 10

**Comment by castwide** [comment]
It sounds like the extension isn't activated. Do you have a file with an `.rb` extension open? There's a known issue where most files without `.rb`, including untitled files, do not get handled by Solargraph's language server, even if their language mode is Ruby.

**Comment by castwide** [comment]
I'll also add a more descriptive error message to the next version of the extension, e.g., "The language server is still initializing. Please try again shortly."

**Comment by jpmachado99** [comment]
My files are only .rb or .yml in this project. I can restart the solargraph server but the error appears when I try to Download current ruby documentation. (The error message changes because I updated the extension to the newer version I suppose.)

**Comment by jpmachado99** [comment]
Add a more descriptive error message is a great idea!

**Comment by castwide** [comment]
What happens when you open an .rb file? You should get a status message in the lower left that says "Starting the Solargraph language server." After it changes to "Solargraph is ready," the language server features should work. (VS Code lazy-loads extensions, so it won't activate the Solargraph extension until it thinks you need it.)

**Comment by jpmachado99** [comment]
When I open an .rb this message you said doesn't appear for me... I still can't download the documentation ("An error occurred while downloading documentation")

**Comment by castwide** [comment]
Can you run `solargraph -v` on a command line? It should tell you which version it's running.

It almost sounds like you don't have the gem installed, but if that's the case, VS Code should tell you so in an error message.

**Comment by jpmachado99** [comment]
$ solargraph -v
0.32.3

It doesn't give me an error message...

**Comment by castwide** [comment]
Do you get any messages in the VS Code console? (From the menu: Help -> Toggle Developer Tools)

Are you using WSL?

**Comment by jpmachado99** [comment]
when i try to install de doc again this messages appears in the console

![image](https://user-images.githubusercontent.com/47401366/58490037-cede2380-8142-11e9-9899-b3deb32cbea7.png)

**Comment by castwide** [comment]
I'm afraid I'm not sure what the problem is here.

Based on your terminal prompt, it looks like you might be using Ruby from WSL or some kind of VM. If that's the case, I think there are ways to access it from VS Code, but I haven't tried it myself. (I'm pretty sure other people have connected to Solargraph running from WSL, Docker containers, etc.)

At the same time, however, the console seems to indicate that Ruby and Solargraph are installed on Windows, so it should still work.

**Comment by jpmachado99** [comment]
i have docker toolbox installed on my PC but I'm not using at the moment because this project is for study purposes only. I'm using Ruby 2.5.5 which is installed on Windows too.

Now the version is 0.32.4

**Comment by jpmachado99** [comment]
When i try to run `solargraph download-core` i got those errors:

![solargraph-error](https://user-images.githubusercontent.com/47401366/58492163-bff97000-8146-11e9-9fd4-c16db77d195b.png)

**Comment by castwide** [comment]
Okay. It looks like there are two problems here. I'm not sure if they're related.

First, the executable should download the core docs from https://solargraph.org. Are you behind a proxy server? Can you connect to solargraph.org from a browser?

Second, the extension should still work, even if download-core doesn't.

What version of the VS Code extension are you using? Current is 0.19.6.

**Comment by jpmachado99** [comment]
i don't know why, but after I updated the gem, the autocomplete and inline doc started to work.
`$ solargraph -v
0.32.4`

It seems the extension is working...

**Comment by jpmachado99** [comment]
I can connect to solargraph.org normally.

**Comment by castwide** [comment]
Cool. At least the extension works.

You should be able to document the gems now. From the command palette, `Solargraph: Build new gem documentation`. From the command line, `yard gems`.

I'm not sure why `download-core` doesn't work, though. No idea where it's getting that bad URI (172.17.80.2:3128). That's not solargraph.org's IP address, and it should connect over HTTPS (port 443), not 3128.

The gem ships with documentation for Ruby 2.2.2. That should work well enough in the meantime; the core and stdlib shouldn't be much different in 2.5.

**Comment by jpmachado99** [comment]
Now the "solargraph is ready" message appears on the lower left side. 

What I wanted is working, thanks for the help.
