### ISSUE TITLE
Can this extension not use an internal language server? 

### ISSUE THREAD

**Issue by guledali** [castwide/vscode-solargraph#123]
@castwide Instead of having to install the `solargraph` gem locally how about implement an internal language server based on the toolkit Microsoft provides in `vscode-languageserver`

**Comment by castwide** [comment]
Solargraph depends on the Ruby runtime environment to select a Ruby version for the core documentation and gather information about gems. The parsing and static analysis required to power the language server are best performed in Ruby. Even if the language server itself were implemented using vscode-languageserver, it would still need to integrate with a Ruby component to work. Implementing the language server directly in Ruby is more efficient and less fragile.
