### ISSUE TITLE
Cannot start language server after 0.34.0 upgrade

### ISSUE THREAD

**Issue by ijdickinson** [castwide/vscode-solargraph#128]
Solagraph has been working fine for me in VsCode, up to this morning when it installed the 0.34.0 update. Now, I get an error message `Couldn't start client Ruby Language Server`, and console output:

    [Error - 10:46:29] Starting client failed
    Could not locate Gemfile or .bundle/ directory

Developer tools has:

    workbench.main.js:2379 Couldn't start client Ruby Language Server
    onDidNotificationChange @ workbench.main.js:2379
    workbench.main.js:238 [Extension Host] Error starting Solargraph socket provider Could not locate Gemfile or .bundle/ directory

    workbench.main.js:2379 Failed to start Solargraph: Could not locate Gemfile or .bundle/ directory
    onDidNotificationChange @ workbench.main.js:2379
    workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: Could not locate Gemfile or .bundle/ directory

    t.log @ workbench.main.js:238
    workbench.main.js:1406   ERR Could not locate Gemfile or .bundle/ directory

Solargaph does seem to be installed OK, and working from the command line:

    $ solargraph -v
    0.34.0
    $ solargraph socket
    Solargraph is listening PORT=7658 PID=23744

Manually reverting to Solargraph 0.33.0 (and disabling the version check in VsCode settings) has got me back to a working version.

I'm running Ubuntu 19.04 with Ruby 2.5.5.

**Comment by castwide** [comment]
Do you have `solargraph.useBundler` set to true? That would cause the error if you open a folder that doesn't have a Gemfile. (Paradoxically, it will work if you open an individual file instead of a folder.)

**Comment by ijdickinson** [comment]
@castwide That setting was initially off, but I did try with it set to `true`. It didn't change the behaviour I was seeing.

**Comment by castwide** [comment]
Okay. I was able to reproduce the error by opening a file that contains either `require 'bundler/require'` or `Bundler.require`. That makes the server look for gem dependencies to add to the map. If it doesn't find a Gemfile, you get the error.

I'll release a patch later today.

**Comment by ijdickinson** [comment]
Great, thanks @castwide

**Comment by castwide** [comment]
Fix pushed in gem v0.34.1.

**Comment by ijdickinson** [comment]
Confirmed fixed. Thanks for the quick response!
