### ISSUE TITLE
Gem not Found - AWS Partitions - Failed to start Solargraph

### ISSUE THREAD

**Issue by tonydehnke** [castwide/vscode-solargraph#129]
Getting these two errors today when starting up VS Code Version 1.35.1 (1.35.1)

Failed to start Solargraph: Error: [Bundler::GemNotFound] Could not find aws-partitions-1.177.0 in any of the sources

[Bundler::GemNotFound] Could not find aws-partitions-1.177.0 in any of the sources

Extension Info:
Name: Ruby Solargraph
Id: castwide.solargraph
Description: A Ruby language server featuring code completion, intellisense, and inline documentation
Version: 0.19.6
Publisher: Castwide
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=castwide.solargraph

**Comment by castwide** [comment]
Solargraph gem v0.34.1 includes a fix to a bundler-related bug that might impact this issue. Try updating them gem and let me know if you still have a problem.

**Comment by tonydehnke** [comment]
Updated today and I am no longer receiving the error message.
