### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by noelrocha** [castwide/vscode-solargraph#131]
- Issue Type: `Bug`
- Extension Name: `solargraph`
- Extension Version: `0.19.6`
- OS Version: `Linux x64 4.18.0-25-generic`
- VSCode version: `1.36.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"startup": false,
		"codeLoadingTime": 253,
		"activateCallTime": 8,
		"activateResolvedTime": 35,
		"activationEvent": "onLanguage:ruby"
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "[NoMethodError] undefined method `name' for nil:NilClass"
		}
	]
}
```

**Comment by castwide** [comment]
Try running `solargraph scan -v` from your workspace's root directory. If it encounters a problem analyzing your code, it should output the last location it tried to analyze and the resulting error. More information: https://solargraph.org/guides/scanning-workspaces
