### ISSUE TITLE
ailed to start Solargraph: Error: [Gem::ConflictError]

### ISSUE THREAD

**Issue by sbehrens** [castwide/vscode-solargraph#132]
Hello, 

I get the following exception using this with vscode:

```
Failed to start Solargraph: Error: [Gem::ConflictError] Unable to activate rdoc-4.2.2, because json-2.2.0 conflicts with json (~> 1.4)
```

Any ideas on what the issue is?

**Comment by castwide** [comment]
You might need to update the RDoc gem. Checking on two different systems with working installations of Solargraph, one uses Ruby 2.3.0 with RDoc 4.3.0, and the other uses Ruby 2.5.3 with RDoc 6.1.1.

**Comment by sbehrens** [comment]
LGTM, thanks for the tip
