### ISSUE TITLE
HTML tags displayed in documentation

### ISSUE THREAD

**Issue by denismcdonald** [castwide/vscode-solargraph#144]
Hello!

I just flag that I'm witnessing an issue that was raised previously [here](https://github.com/castwide/vscode-solargraph/issues/4) and subsequently closed; namely, that HTML tags are being displayed in documentation, both when hovering over code and when pressing Ctrl+space.  This is on Windows 10, using Visual Studio Code version 1.38.1.

Below are a couple of screenshots, if it assists.

![Solargraph HTML tags1](https://user-images.githubusercontent.com/14754197/65494955-2fb31800-def9-11e9-95f6-2755efcfacf6.JPG)

![Solargraph HTML tags](https://user-images.githubusercontent.com/14754197/65494960-35106280-def9-11e9-807c-e52ae515a358.JPG)

**Comment by castwide** [comment]
Fixed in gem version 0.38.0.
