### ISSUE TITLE
Error installing solargraph:

### ISSUE THREAD

**Issue by xclidongbo** [castwide/vscode-solargraph#145]
Building native extensions. This could take a while...
ERROR:  Error installing solargraph:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.3/ext/jaro_winkler
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20190925-60069-63nvho.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/jaro_winkler-1.5.3 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/jaro_winkler-1.5.3/gem_make.out

**Comment by castwide** [comment]
Have you tried installing XCode as described in #78?

**Comment by xclidongbo** [comment]
Yes, but It does`t work.

**Comment by castwide** [comment]
There are additional comments in #78 about MacOS 10.14 that might help.

**Comment by xclidongbo** [comment]
@castwide Thanks.
