### ISSUE TITLE
[Feature Request] Add additional options for Ruby documentation search

### ISSUE THREAD

**Issue by Mawdac** [castwide/vscode-solargraph#149]
Hello! I'll start by saying that this extension is awesome! Massive thanks @castwide , as it has made my life much easier in the past couple months.

With that said, here's my feature request:

**There should be additional options for filtering the Ruby documentation when using the 'search Ruby documentation' functionality.**

I find that this functionality is extremely helpful (especially as someone relatively new to Ruby), but because it includes the current workspace, it also causes some unexpected issues.

Example:

When I use the Ruby search functionality in a workspace that does not have any ruby files or gems, the search works pretty much as expected:

![Screen Shot 2019-11-05 at 1 31 17 PM](https://user-images.githubusercontent.com/8498296/68235095-9f282700-ffd0-11e9-9450-db30fc738eb5.png)

Now if I open my Ruby project as the current workspace, and then search for `string`, I get this:

![Screen Shot 2019-11-05 at 1 34 23 PM](https://user-images.githubusercontent.com/8498296/68235296-ff1ecd80-ffd0-11e9-873a-2f23ed61c7ae.png)

I understand this is because the diff-lcs package is "redefining" the `String` class, but I want to be able to filter things in my current workspace out so that doesn't happen. When this happens, there is no way for me to get to the Ruby core or stdlib doc reference.

**Suggestions:**
* A set of checkboxes, or a dropdown in settings would be really nice so that I could only search in the Ruby core and stdlib.
* Mutiple results for `string` when it applies (or any other searched term) - including those in the core, stdlib, required gems, and current workspace (I don't know if that would be harder or easier to implement)

I hope this makes sense - if I can add any additional info that would help please let me know, and thanks again for this awesome extension!

**Comment by castwide** [comment]
Thanks! I'm glad you find it useful.

I confirmed this issue with a workspace that defines a trivial `String` class. Fixing it will require a change to the way the `$/solargraph/document` message queries code maps. The first step is to make it combine local documentation with documentation from gems and the Ruby core; I think the default behavior should be to provide everything. From there, we should be able to add a filter for selecting documentation from particular sources.

**Comment by Mawdac** [comment]
Agreed that the default should be to provide everything - if that was the case, the filter I described is probably not even necessary since it displays all results, maybe just something in the search results to categorize the sources.

**Comment by castwide** [comment]
Yeah, I think you're right. Adding a filter to the doc page should be easier to implement and more practical for the user.

**Comment by Mawdac** [comment]
Don't know when this was changed but I love the new documentation view - thanks @castwide !
