### ISSUE TITLE
Multi-root workspace support

### ISSUE THREAD

**Issue by castwide** [castwide/vscode-solargraph#15]
Update the extension to support multi-root workspaces (https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs).

This issue may also require enhancements to the solargraph gem and the solargraph-utils package.

**Comment by castwide** [comment]
First implementation of multi-root workspace support is in v0.11.0.

**Comment by voter101** [comment]
Is there any update on this issue? I work on multiple Ruby projects in one workspace and autocomplete does not load any files from those projects. It workes perfectly well for autocompleting stdlib things.

The extension works as intended when I load only a single project in a workspace.

Is there any way I can help you with that?

**Comment by castwide** [comment]
Since the server now uses the language server protocol, the majority of work to support multi-root workspaces should be handled in the [gem](http://github.com/castwide/solargraph). I'll add it to the roadmap and start a branch for it.

**Comment by castwide** [comment]
Multi-root workspace support is an upcoming gem feature. It's being tracked in castwide/solargraph#114.
