### ISSUE TITLE
Hangs on starting the language server from solargraph version 0.34 and up

### ISSUE THREAD

**Issue by Frydac** [castwide/vscode-solargraph#152]
Hi,

While solargraph 0.33 and earlier work as expected, when I install solargraph versions 0.34, 0.35, 0.36, 0.37 and 0.38, then vscode prints in the status line:
`Starting the solargraph language server`  
with some animation, but never ends, and it doesn't work (e.g. no completions). I can see in my 'system monitor' that the solargraph executable has started.
I'm on manjaro linux with
```
~   
▶ code -v
1.40.0
86405ea23e3937316009fc27c9361deee66ffbf5
x64

~   
▶ ruby -v                              
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
```
and extension information:
```
Name: Ruby Solargraph
Id: castwide.solargraph
Description: A Ruby language server featuring code completion, intellisense, and inline documentation
Version: 0.21.1
Publisher: Castwide
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=castwide.solargraph
```

When I install solargraph 0.33 I don't seem to have these problems.

(vim with coc.nvim coc-solargraph seems to have problems aswell with these versions, but I can't see any logs with errors there, or I don't know how to)

Any suggestions on how to debug this? Or maybe I should ask in the solargraph issues?

**Comment by castwide** [comment]
The extension worked for me on a Manjaro VM opening a workspace folder with a single empty .rb file. I used Ruby 2.6.3 and Solargraph 0.8.3. Can you see if that works for you? If it does, the problem might be specific to the workspace you're trying to open.

A couple things that could help you troubleshoot:

* Do you get any error messages in the developer console? (Help -> Toggle Developer Tools)
* Try running `solargraph scan -v` on your workspace to detect problems parsing and mapping the code. More information: https://solargraph.org/guides/scanning-workspaces

**Comment by Frydac** [comment]
Thanks,

On my work desktop, which runs all the same software afaik, solargraph 0.38 seems to work as expected. Not sure what is different at home.
I just created a new folder with an empty test.rb file, and start typing `File` or `String` or so (when it doesn't hang of course)
I'll close this for now, I'll figure it out, thanks
