### ISSUE TITLE
diagnostics ignoring .rubocop.yml excludes

### ISSUE THREAD

**Issue by Zhorian** [castwide/vscode-solargraph#155]
When using rubocop diagnostics I expect it to utilise the .rubocop.yml config at the root of my project, this doesn't seem to be the case as I'm getting errors on a file I've excluded. The yml file is picked up if I run rubocop from the command line. The same issue seems to be happening with [vscode-ruby](https://github.com/rubyide/vscode-ruby/issues/578).

![image](https://user-images.githubusercontent.com/32066442/72170477-dba94200-33c8-11ea-9048-9552efb44f10.png)

settings.json
`{
    "editor.formatOnSave": true,
    "editor.formatOnSaveTimeout": 5000,
    "emmet.includeLanguages": {
        "html.erb": "html",
        "erb": "html"
    },
    "powermode.enabled": true,
    "powermode.enableShake": false,
    "ruby.useLanguageServer": true,
    // "ruby.lint": {
    //     "rubocop": {
    //         "useBundler": true
    //     }
    // },
    "ruby.format": "rubocop",
    "ruby.useBundler": true,
    "solargraph.diagnostics": true,
    "workbench.colorTheme": "Blueberry Banana",
    "workbench.iconTheme": "vscode-icons",
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "files.autoSave": "afterDelay"
}`

.rubocop.yml
`AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "**/*.erb"
    - db/schema.rb
    - "bin/**/*"
    - "node_modules/**/*"
    - test/test_helper.rb
    - test/channels/application_cable/connection_test.rb`

.solargraph.yml
`AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "**/*.erb"
    - db/schema.rb
    - "bin/**/*"
    - "node_modules/**/*"
    - test/test_helper.rb
    - test/channels/application_cable/connection_test.rb`

**Comment by castwide** [comment]
The way RuboCop handles `excluded_files` is a little confusing. When you run RuboCop on a directory, it uses the configuration. When you run it on a specific file, it assumes that you want a report regardless of whether the file is excluded. Solargraph runs RuboCop on the file when you open it in an editor, so you get the latter behavior.

It's hard to say which option is correct. Some users might want to see diagnostics while they're in the process of editing an excluded file, even if it won't appear in directory reports. Others might not.

The current workaround is to add a `.rubocop` file with the following:

```
---force-exclusion
```

**Comment by Zhorian** [comment]
Thanks that worked  except I think you may have added an extra dash?

`--force-exclusion` worked for me!
