### ISSUE TITLE
[LoadError] cannot load such file -- irb/slex

### ISSUE THREAD

**Issue by kamillle** [castwide/vscode-solargraph#157]
solargraph version: 0.38.2
ruby version: 2.7.0
OS: Catalina 10.15.2
VSCode: 1.41.1
StackTrace: Just appears below 😢 
```
[Error - 21:08:33] Server initialization failed.
  Message: [LoadError] cannot load such file -- irb/slex
  Code: -32603 
```

I've seen https://github.com/castwide/vscode-solargraph/issues/137 and updated irb gem, but same error cames up.

**Comment by castwide** [comment]
There are some issues around `irb` that affected a lot of gems in Ruby 2.7. Try updating the `solargraph` gem first. The current version is 0.38.5. If that doesn't help, try updating the `yard` gem. (The latter shouldn't be necessary, but if it is, there might be an issue with Solargraph's gem dependencies.)

Related info: https://github.com/castwide/solargraph/issues/233

**Comment by kamillle** [comment]
@castwide The infomation is perfect for me!! Thank you for your kindness!!
