### ISSUE TITLE
Prevent format on save

### ISSUE THREAD

**Issue by josemigallas** [castwide/vscode-solargraph#158]
Hi, whenever I try to format my document (manually), the following error pops up:
![Screen Shot 2020-01-30 at 09 41 17](https://user-images.githubusercontent.com/11672286/73433404-f83ff680-4344-11ea-95c3-a0e709b90356.png)

However if `"solargraph.formatting"` is `true`, then it will always format on save regardless of `"editor.formatOnSave"` being `false`.

Is there a workaround for this? Would it be possible to allow formatting at will?

**Comment by castwide** [comment]
I haven't been able to reproduce this problem. With `solargraph.formatting: true` and `editor.formatOnSave: false`, I get the expected behavior. Could another extension be ignoring the `formatOnSave` option and triggering the format?
