### ISSUE TITLE
Intellisense don't autocomplete

### ISSUE THREAD

**Issue by StefanoPernat** [castwide/vscode-solargraph#16]
The intellisense seems not to work properly when calling multiple methods on one line
![solargraph_issue](https://user-images.githubusercontent.com/9131699/32663319-e223207a-c62d-11e7-83f7-b043c53999e0.jpg)

I'm using VSCode on a Windows 7 pc

**Comment by castwide** [comment]
Confirmed. The problem appears specific to Kernel methods that should be available from any namespace. The gem recognizes that `gets` and `Kernel.gets` both return String, but fails to infer them from chained methods.

In contrast, chained methods from the String class work as expected:

![solargraph-chomp](https://user-images.githubusercontent.com/3704922/32677540-dbdd1d16-c62c-11e7-9833-a159718dccf9.png)

This is almost certainly a bug in the gem itself.

**Comment by castwide** [comment]
Bug fix pending gem v0.14.0: https://github.com/castwide/solargraph/issues/16

**Comment by castwide** [comment]
Fixed in gem v0.14.2.
