### ISSUE TITLE
[Feature request] Also show @return description on method hover.

### ISSUE THREAD

**Issue by derkallevombau** [castwide/vscode-solargraph#162]
It would be awesome if the hover window also contained the description provided via a method's @return tag, not just the type.

**Comment by castwide** [comment]
Good idea. I'll add it to the roadmap.

**Comment by derkallevombau** [comment]
Ok, thank you!

**Comment by castwide** [comment]
Gem version 0.39.1 displays return tag descriptions in completion and hover windows.
