### ISSUE TITLE
[ArgumentError] marshal data is too short

### ISSUE THREAD

**Issue by anks333** [castwide/vscode-solargraph#170]
Tried to start the language server but getting `[ArgumentError] marshal data is too short` and `[ArgumentError] marshal data too short` alert.

Error Log
```
[Error - 4:00:39 PM] Server initialization failed.
  Message: [ArgumentError] marshal data too short
  Code: -32603 
```

**Comment by castwide** [comment]
You might have a bad cache. Try running `solargraph clear`.

**Comment by castwide** [comment]
Gem version 0.39.3 handles cache errors more gracefully.

**Comment by anks333** [comment]
Yes, it's working now, but autofix is not working. Tried with rubocop but
no luck.


Could you please help me setup vs code for ruby development,
I'm little confused with which extension to install, there are many
extension but don't know which will work properly. If I installed multiple
extension then they may not be compatible.

What all extension should I install apart from ruby-solargraph

**Comment by castwide** [comment]
Solargraph doesn't currently support format on type or quick fixes, but it uses RuboCop for format on save and the Format Document command.

I don't know of any specific conflicts with other extensions. The other Ruby extensions I use frequently are [rebornix.Ruby](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby) and [castwide.ruby-debug](https://marketplace.visualstudio.com/items?itemName=castwide.ruby-debug) (the latter of which is also mine). Both work fine with Solargraph.
