### ISSUE TITLE
Formatter running infinetly

### ISSUE THREAD

**Issue by Vearmox** [castwide/vscode-solargraph#173]
When i try to save an .rb file a window stating 
`Saving 'xxxxxx.rb': Running 'Ruby Solargraph' Formatter (configure).`
pops u and it keeps running forever without saving the file. 
I tried reinstalling the solargraph gem, the extension, rvm, ruby itself but it wont help and im still getting the same error. 
Im running MacOs Mojave and ruby 2.6.6 (same version stated in `.ruby-verision` file
Other extensions formatters work(ruby-rubocop) for example.

**Comment by henriquetatagiba** [comment]
I was facing the same error just now.

In my case, I just replace on `settings.json`:

```jsonc
"solargraph.autoformat":  true // <-- remove this
````
to 
```json
"editor.formatOnSave": true,
````

**Comment by henriquetatagiba** [comment]
Happens with me when I try to save a file with special characters (é, ã, ê, ç...) in it.

If I remove those chars and restart vscode, the solargraph will work again.

**Comment by castwide** [comment]
Do either of you get a backtrace in the developer console (Help -> Toggle Developer Tools)?

**Comment by Vearmox** [comment]
> Environment Info:
> MacOS High Sierra
> VS Code: 1.44.2
> Solargraph Gem: 0.39.7
> Ruby Solargraph Plugin: 0.21.1
> Ruby: 2.6.6p146
> 
> Happens with me when I try to save a file with special characters (é, ã, ê, ç...) in it.
> 
> If I remove those chars and restart vscode, the solargraph will work again.
> 
> Maybe there's something to do with [this issue](https://github.com/castwide/solargraph/issues/33)

You were right. Its letters like Ä which break the formatter (even if its just a string). Is there any way to fix this?

**Comment by henriquetatagiba** [comment]
> Do either of you get a backtrace in the developer console (Help -> Toggle Developer Tools)?

@castwide, here's my console when I save a file with special characters:

![image](https://user-images.githubusercontent.com/16236873/81287912-fd929880-9039-11ea-8743-a0aecf4732af.png)

**Comment by castwide** [comment]
The latest version of the gem (0.39.11) declares UTF-8 as the default external encoding. I'm closing this issue since the same bug is being tracked in #166. Please feel free to comment there if the problem persists.
