### ISSUE TITLE
[Error - 3:55:07 PM] Starting client failed

### ISSUE THREAD

**Issue by lacostenycoder** [castwide/vscode-solargraph#174]
Opened latest version of VSCode Version: 1.45.0 on MacOS
Got this error, no terminal output or anything else.

**Comment by castwide** [comment]
Anything in the developer console? (Help -> Toggle Developer Tools)

What versions of Ruby and the Solargraph gem are you using?

**Comment by lacostenycoder** [comment]
may have been my firewall... gonna close for now.
