### ISSUE TITLE
Odd behavior when using yard `@!parse` and code completion

### ISSUE THREAD

**Issue by olbrich** [castwide/vscode-solargraph#176]
![image](https://user-images.githubusercontent.com/22176/82973890-95830280-9fa6-11ea-8a28-56d3ac18064e.png)

Using solargraph 0.39.7 and ruby 2.6.5

Note that the default argument of the parsed class method is pulling in a chunk of the comment on the top level class.

The rendered yard docs are correct and do not have this problem.

**Comment by castwide** [comment]
Confirmed. I'll have it fixed in the next release.

**Comment by castwide** [comment]
This should work as expected in the latest gem (0.39.11).
