### ISSUE TITLE
Please add a function to close the solargraph service when I close the editor or add a button to close it, Thank you!

### ISSUE THREAD

**Issue by goe13** [castwide/vscode-solargraph#177]

**Comment by castwide** [comment]
I'm not sure this is feasible. Solargraph starts whenever the extension gets activated, most often because a Ruby file was opened in an editor. There's some overhead involved in starting the language server, so once it's initialized, it stays open for the duration of the session. This is typical behavior for all language servers. (If you mean the language server keeps running after you close VS Code altogether, that's a different issue.)

**Comment by goe13** [comment]
You are right. The language server keeps running after I close VS Code altogether.

**Comment by castwide** [comment]
* What OS, Ruby version, and Solargraph version are you using? (You can get a lot of information about your environment by running "Solargraph: Get environment info" from the VS Code command palette.)
* Can you give me a reproducible example of a workspace that leaves Solargraph running after you close VS Code?

**Comment by goe13** [comment]
### Solargraph Environment Info
##### System
* Platform: x86_64-darwin19
* Shell: /bin/zsh
* Ruby Version: 2.7.1
* RuboCop Version: 0.82.0
##### Solargraph
* Solargraph Version: 0.38.6
* Core Documentation Version: 2.2.2
* Core Cache Directory: /Users/eos/.solargraph/cache
* Parser Target Version: 27
* Using Bundler: false
##### Project
* Config: {"completion"=>true, "hover"=>true, "symbols"=>true, "definitions"=>true, "rename"=>true, "references"=>true, "autoformat"=>false, "diagnostics"=>false, "formatting"=>false, "folding"=>true, "logLevel"=>"warn", "enablePages"=>true, "viewsPath"=>"/Users/eos/.vscode/extensions/castwide.solargraph-0.21.1/views", "transport"=>"socket", "externalServer"=>{"host"=>"simp.top", "port"=>7658}, "commandPath"=>"solargraph", "useBundler"=>false, "bundlerPath"=>"bundle", "checkGemVersion"=>true}
* Workspace folders: ["/Users/eos/my-docs/learn/Ruby/class1"]

**Comment by goe13** [comment]
![image](https://user-images.githubusercontent.com/5849419/83959683-8196a500-a8b2-11ea-9b49-a0d3035410d9.png)

**Comment by goe13** [comment]
When I close VScode, it runs at least one solargraph process.
![image](https://user-images.githubusercontent.com/5849419/83959763-b5be9580-a8b3-11ea-82ed-94e9b21422a0.png)

**Comment by goe13** [comment]
It's fixed.
