### ISSUE TITLE
please provide documentation on how to develop the extension itself

### ISSUE THREAD

**Issue by doudou** [castwide/vscode-solargraph#178]
I wanted to make a minor addition to the extension, but did not manage to test it.

I've tried the `npm install` route, but then I get an error on server start,

~~~
Cannot find module ./spinner
~~~

I'm really not familiar with the javascript packaging tools - I know just enough typescript/javascript to handle development.

**Comment by castwide** [comment]
To install and run a local build, you probably need to run `npm run build` first.

The easiest way to test an extension under development is to run it from VS Code's debugger. This repo includes a "Launch Extension" configuration in the `launch.json` file. More information: https://code.visualstudio.com/api/get-started/your-first-extension
