### ISSUE TITLE
[Question] How to extend solargraph's Go To Definition?

### ISSUE THREAD

**Issue by judocode** [castwide/vscode-solargraph#189]
I am having a hard time deciphering how exactly Go To Definition is implemented in solargraph and I would like to fork the code to create a more specific implementation of it. Is there some sort of documentation or code that describes how this might be done?

Thanks!

**Comment by castwide** [comment]
You'll probably want to make that change in the [gem](https://github.com/castwide/solargraph) instead of the VS Code extension. I'd start by looking at `Library#definitions_at` and how it uses `Clip#define` (for code) or `Clip#translate` (for tags in comments) to retrieve the pins.
