### ISSUE TITLE
Failed to install on mac

### ISSUE THREAD

**Issue by prettyGoo** [castwide/vscode-solargraph#19]
I tried to install this extension on my mac, but got next error: Solargraph gem not found. Run `gem install solargraph` or update your Gemfile. 
When I run the command in the terminal, got next error. Any idea  why it is happening?
![image](https://user-images.githubusercontent.com/13743115/35551450-ba254f2a-05c1-11e8-83b9-fa054b2564d4.png)

**Comment by castwide** [comment]
Version 0.11.3 of the extension should fix part of this issue. If you're able to install the gem, the extension should work correctly with Ruby installation managers like RVM or rbenv.
