### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Tonifong** [castwide/vscode-solargraph#192]
- Issue Type: `Performance`
- Extension Name: `solargraph`
- Extension Version: `0.21.1`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.48.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\welco\castwide.solargraph-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by castwide** [comment]
This is a common issue, especially with very large codebases. I'm going to close this as a duplicate since performance is being addressed elsewhere.
