### ISSUE TITLE
Lint error with / operator

### ISSUE THREAD

**Issue by NuriYuri** [castwide/vscode-solargraph#194]
- Issue Type: Visual or Lint
- Extension Name: solargraph 
- Extension Version: 0.21.1
- OS Version: Windows 10 Pro, 18362.1082 (1903)
- VSCode version: 1.49.0
- Gem Version: 39.15

Hi, I have a little lint error when I'm using the operator `/` for division, it thinks its a regular expression. It's really weird, I don't know if that comes from Visual Studio Code or Solar Graph itself but here's what I see when I'm using this operator:

![image](https://user-images.githubusercontent.com/7335788/93667191-244eea00-fa84-11ea-8da7-851c5215e374.png)

**Comment by castwide** [comment]
This appears to be an issue with VS Code's built-in syntax highlighting. Solargraph doesn't perform any syntax highlighting at all.
