### ISSUE TITLE
Go to Definition for included methods

### ISSUE THREAD

**Issue by alextakitani** [castwide/vscode-solargraph#199]
I have a rails app that has some concerns.

When I try to use go to definition, it does not find the methods.

Is there something I can do about it on the config?

Thanks!

**Comment by castwide** [comment]
Improving Rails support is a work in progress. You can see more about it here: https://github.com/castwide/solargraph/issues/87

I'm going to close this issue as a duplicate, but please feel free to post questions or comments in the other one.
