### ISSUE TITLE
Separate icons for snippets and keywords.

### ISSUE THREAD

**Issue by AndyBay** [castwide/vscode-solargraph#2]
When starting to write "class" or "if", Solargraph suggests snippets using the keyword icon.

In Python (as seen under), separate icons are used (top = keyword, bottom = snippet).
In VS Code you can turn off snippet suggestions, but Solargraph still suggests them.
![py_keyw_snipp](https://cloud.githubusercontent.com/assets/1170184/25783498/3a2953a2-335d-11e7-8ac4-81094cd0ceb7.png)

**Comment by castwide** [comment]
Thanks for the report. Mixing snippets into Solargraph's suggestions was an early experiment, but it's probably best to remove them altogether. They're based on the rebornix.Ruby snippets, so anyone running both extensions can still get them.

Sending snippets from the gem should have been disabled by default, but a bug caused them to be inserted anyway. The next version will correct it.

**Comment by castwide** [comment]
The gem and extension are both updated.

* The gem's completion server accepts a parameter from the client telling it whether to include snippets in suggestions. It excludes snippets by default.
* The extension has a withSnippets setting to determine whether to request snippets from the server. It's set to false by default.

**Comment by AndyBay** [comment]
Thank you for the quick update, it seems to work great now :)
