### ISSUE TITLE
Basic completion results in unexpected token

### ISSUE THREAD

**Issue by raldred** [castwide/vscode-solargraph#21]
I have a based ruby example that is not completing at all.
https://www.dropbox.com/s/kv7z4ldn5wrw1ex/Screenshot%202018-02-01%2014.54.09.png?dl=0

I type `[1,2,3].` and the following error turns up in the developer tools and I don't get any suggestions

```
[Extension Host] (string):30:12: error: unexpected token tIDENTIFIER
(string):30:     [1,2,3]_
```

**Comment by castwide** [comment]
Thanks, @raldred. There's a bug resolving literal values (strings, arrays, etc.) that's been resolved in the castwide/solargraph master branch. It should work correctly in the next version of the gem.

**Comment by raldred** [comment]
Thanks, look forward to that rolling through.
