### ISSUE TITLE
Method Arguments in wrong order

### ISSUE THREAD

**Issue by NeilBurkholder** [castwide/vscode-solargraph#211]
I don't know if there is some setting that is wrong, but I've been noticing that for some of my methods the arguments show in the wrong order. How would I go about finding and fixing the issue? Are the some settings to check?

![image](https://user-images.githubusercontent.com/24275193/109527177-5fb50200-7a81-11eb-8c0e-6ab1eeded35b.png)

**Comment by castwide** [comment]
This is a known issue that is currently fixed in the gem repo's master branch (https://github.com/castwide/solargraph/commit/3d3fd32a794d511e8632df5c6568e61f4c03e88e). The fix will be published in gem version 0.40.4 later this week.

**Comment by castwide** [comment]
Fix released in v0.40.4.
