### ISSUE TITLE
Update popup doesn't work

### ISSUE THREAD

**Issue by philliplongman** [castwide/vscode-solargraph#213]
Every time I start VS Code, I'm getting the popup telling me that `Solargraph 0.40.4` has been released. If I click `Update Now`, it claims to have updated the gem, but in reality, nothing has happened.

I know how to manually update the gem, but I thought I should report this.

**Comment by hp-plus5** [comment]
I also have this problem, but without the know-how to manually manage the VS Code extension.

**Comment by philliplongman** [comment]
It's not the extension that needs to be updated, it's the Solargraph gem. You need to run `gem install solargraph` in the same directory as your project. If you have multiple projects that use different versions of Ruby, you may need to do that in each one. Just do it again when you see the popup.

**Comment by castwide** [comment]
If anyone still has problems with the update button, please refer to #224.
