### ISSUE TITLE
Message: [Solargraph::FileNotFoundError] Host could not find file:/

### ISSUE THREAD

**Issue by arcman7** [castwide/vscode-solargraph#218]
Error - 8:27:20 PM] Request textDocument/documentSymbol failed.
  Message: [Solargraph::FileNotFoundError] Host could not find file:/
  
 [Ref](https://github.com/castwide/vscode-solargraph/issues/47)
  > I'm closing this issue since the original problem with FileNotFoundError should be resolved. If anyone still has problems with either that or CPU usage, please open a new issue.
  
That's what I'm doing now. 

I installed this vs code extension and this has started happening every time I open a ruby file, but also when I try look up definitions from a ruby file.

Operating system
==============
mac OS Big Sur

Visual Studio Code
==============
Version: 1.55.1 (Universal)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.3.0

**Comment by mikekytyzov** [comment]
same for me

```
[Error - 12:48:52 PM] Request textDocument/documentSymbol failed.
  Message: [Errno::ENOENT] No such file or directory @ dir_chdir - 
  Code: -32603 
[Error - 12:48:52 PM] Request textDocument/hover failed.
  Message: [Errno::ENOENT] No such file or directory @ dir_chdir - 
  Code: -32603 
```

BigSur 11.4 

solar v0.23.0
vscode Version: 1.57.0

**Comment by UrsaDK** [comment]
Just to expand on what @mikekytyzov is saying: Here is **Log (Extension Host)** error corresponding to the above **Ruby Language Server** error.

```
[2021-06-11 11:48:24.654] [exthost] [error] [castwide.solargraph] provider FAILED
[2021-06-11 11:48:24.654] [exthost] [error] Error: [Errno::ENOENT] No such file or directory @ dir_chdir - 
    at handleResponse (~/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (~/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (~/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (internal/timers.js:461:21)
```

**Comment by castwide** [comment]
Gem version 0.42.1 should fix this error.

**Comment by mikekytyzov** [comment]
@castwide 

```
solargraph -v
0.42.0
```

<img width="797" alt="Screenshot 2021-06-11 at 14 24 13" src="https://user-images.githubusercontent.com/21098110/121679163-b4283e80-cac0-11eb-90a3-5a559f91bde5.png">

v.023 i meant, that vscode show me this version

**Comment by UrsaDK** [comment]
Yep, 0.42.1 is working just fine for me now. 
Thanks @castwide, much appreciated indeed!

**Comment by mikekytyzov** [comment]
@castwide thanks, 0.42.1 is okay :)

**Comment by arcman7** [comment]
Sweet, gonna try this again!
