### ISSUE TITLE
Mapping workspace hangs up 750/833 [with stdio transport]

### ISSUE THREAD

**Issue by NuriYuri** [castwide/vscode-solargraph#220]
SolarGraph version: 0.41.1  
Problem: The extension hangs up with the notification `Mapping workspace: 750/833 files`  
Ruby Language Server Output:
```
Solargraph is listening on stdio PID=4368
warning: parser/current is loading parser/ruby30, which recognizes
warning: 3.0.0-compliant syntax, but you are running 3.0.1.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
```
Workspace with the error: https://gitlab.com/pokemonsdk/pokemonsdk/-/tree/development/scripts (Note: VSCode always open from the scripts folder!)  

I've tried to run the command: `solargraph scan -v`  
The first time it crashed at a script so I made a commit to fix the issue and ran the command again, the command completed but for some reason the mapping does not work when I reopen VSCode :\
![image](https://user-images.githubusercontent.com/7335788/120291017-2cbe1c80-c2c3-11eb-8626-927e1ac6966a.png)

**Comment by castwide** [comment]
I tested opening the `scripts` folder using Ruby 3.0.0. Workspace mapping completed successfully. LSP features like completion and hover worked as expected.

* In my checkout, Solargraph mapped 828 files instead of 833. Do you have untracked .rb files in your workspace?
* Do you have an untracked .solargraph.yml? If so, can you show me your configuration?
* When you open VS Code, which file has focus in the editor?

**Comment by NuriYuri** [comment]
Hello I probably forgot to say I'm running under Windows 10.

- We have been working during the day so the amount of file might have changed ^^ (We're working on pretty big features right now, in my current branch `implement_ability_effect` I have 854 files and it hangs at 769.)

- I don't have a .solargraph.yml file but I have a different settings in user settings:
```
{
    "workbench.settings.useSplitJSON": true,
    "solargraph.useBundler": false,
    "[ruby]": {
        "editor.insertSpaces": true,
        "editor.tabSize": 2
    },
    "files.insertFinalNewline": true,
    "editor.minimap.enabled": false,
    "solargraph.transport": "stdio",
    "solargraph.diagnostics": true,
    "editor.tabSize": 2,
    "yaml.schemas": {
        "file:///c%3A/Users/nuriy/.vscode/extensions/atlassian.atlascode-2.7.1/resources/schemas/pipelines-schema.json": "bitbucket-pipelines.yml"
    },
    "atlascode.bitbucket.enabled": true,
    "atlascode.jira.enabled": false,
    "debug.internalConsoleOptions": "neverOpen",
    "extensions.ignoreRecommendations": true,
    "explorer.confirmDragAndDrop": false,
    "files.eol": "\n",
    "debug.openDebug": "neverOpen",
    "debug.showInStatusBar": "never",
    "workbench.sideBar.location": "right",
    "git.confirmSync": false,
    "diffEditor.ignoreTrimWhitespace": false
}
```
- Last time I opened it was on `01600 Alpha 25 Battle Engine\00200 Battle_Logic\01006 EndTurnHandler.rb`

Just in case here's my ruby -v output: `ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [i386-mingw32]`

**Comment by NuriYuri** [comment]
I just try changing from transport = stdio to transport = socket.
It works perfectly with sockets so I guess it's a bug with the stdio transport ^^

(I use stdio because the connection was very unstable with sockets for some reasons, idk if it improved for now).

**Comment by castwide** [comment]
Thanks for catching that. I confirmed that it hangs using the stdio transport, most likely due to erroneous data being sent to the stdout stream. I'll look into it.

**Comment by mikekytyzov** [comment]
@castwide 

```
solargraph -v
0.42.0
```

sorry, v0.23 i meant from vscode

**Comment by castwide** [comment]
Solargraph gem v0.42.4 includes an update that suppresses some instances of erroneous YARD output.

**Comment by NuriYuri** [comment]
It's working!

Thanks a lot :D
