### ISSUE TITLE
Autocomplete for gems

### ISSUE THREAD

**Issue by bgmat** [castwide/vscode-solargraph#23]
Hi guys!

Is this extension supposed to show suggestions for methods in the gems I use?

Thanks

**Comment by castwide** [comment]
It should, but there are circumstances where some suggestions may be missing or incomplete. There's a known issue with bundled gems that should be fixed in the next version.

If you're having trouble with a particular gem, let me know the details and I'll see if there's a fix.

**Comment by bgmat** [comment]
Hi @castwide 
Thank you for looking into it!
This is the gem I'm using: https://github.com/Shopify/shopify_api

**Comment by castwide** [comment]
During testing, I found a bug that stops the extension from providing suggestions when a workspace (folder) isn't open. It's actually a problem in the API server, not the extension. It'll be fixed in the next version of the gem.

I was able to get Shopify suggestions by doing the following:

* Install the shopify_api gem.
* Open a folder in VS Code.
* Open or create a file with the .rb extension.
* Edit the file.

Results:

![image](https://user-images.githubusercontent.com/3704922/36277767-d5904f3a-125f-11e8-9b89-b5d8188acb10.png)

**Comment by bgmat** [comment]
Yes, it works in this sequence, thanks!
However,I found a case when the results are inconsistent. Maybe you could look into this.

If I type "ShopifyAPI.S" like in the image below, I get one result (popping up as I type)
![image](https://user-images.githubusercontent.com/32710972/36297021-2afa14d0-12f9-11e8-86bf-ba1b86b16dea.png)

but, if I hit escape, then CTRL+Space to get the autocomplete, I get this:
![image](https://user-images.githubusercontent.com/32710972/36297058-5778fbf2-12f9-11e8-83c6-1401ea080938.png)

This is not happening for "ShopifyAPI::S", only for "ShopifyAPI.S" ...

**Comment by castwide** [comment]
Interesting. It appears to be an issue with case sensitivity. With a lower-case S, you get the expected method suggestions. I'll look into it.

**Comment by castwide** [comment]
Incidentally, today's gem version update fixes the API server issue, so completion should work when you don't have a workspace/folder open.

**Comment by castwide** [comment]
In the current gem, completion items in the above cases are better, although case sensitivity can still cause some minor inconsistencies.

* `ShopifyApi.` returns the expected methods. Typing `S` filters without case sensitivity.
* `ShopifyApi.S`, `escape`, and `ctr+space` returns nothing.

This seems reasonable enough to me.

**Comment by castwide** [comment]
This issue should be resolved in the most recent versions of the gem, including the discrepancies between completion filters, which are now case-insensitive by default. If anyone still has problems, please feel free to open a new issue.
