### ISSUE TITLE
Poll: is vscode-solargraph reliable/performant for medium-size Rails apps?

### ISSUE THREAD

**Issue by machty** [castwide/vscode-solargraph#249]
I have a 2015 Apple MacBook Pro (and a new M1 MBP on the way, fortunately), and a few teammates of mine have M1 Macbook Airs. All of us encounter the same thing: for our Rails 6 project that we maintain, Vscode + solargraph starts off just fine, but after a few minutes, it just seems to get bogged down, and linting starts to take 5 seconds, then 10 seconds, and then eventually stuff crashes.

Of course, I'd like to get to the bottom of this, but I kind of wanted to take a poll of vscode-solargraph users:

## Poll Question:

As a vscode-solargraph user on a Rails codebase: does vscode-solargraph work reliably-enough for you that it's A. fast enough, B. gives correct results, C. doesn't slow down other operations, like running tests or reloading Zeitwerk rails code after a code change, and D. you're not constantly thinking about whether Solargraph is about to crash or in need of a reload?

If vscode-solargraph is satisfactory in this regard, please add a 👍 to this issue, and if it is not, or in general you're using vscode-solargraph in some partially functional manner, please add a 👎 .

I'm asking because before I do some perf work on our vscode-solargraph setup, I want to know what's actually possible to attain, or if maybe the underlying technology is still going to be too slow / clunky for things to be fast.

**Comment by castwide** [comment]
Performance tips: https://solargraph.org/guides/performance
Solargraph and Rails: https://solargraph.org/guides/rails
Troubleshooting: https://solargraph.org/guides/troubleshooting
`solargraph-rails` plugin (work in progress): https://github.com/iftheshoefritz/solargraph-rails

If you want to report a bug, request a feature, or ask a specific question, please feel free to open a new issue or post a [discussion](https://github.com/castwide/vscode-solargraph/discussions).
