### ISSUE TITLE
does it support include key word？

### ISSUE THREAD

**Issue by siumennel** [castwide/vscode-solargraph#25]
module MyModule
def helloworld
  puts "helloworld"
end
end
include MyModule
hello

when i type hello then ctrl+space, can it suggest me the helloworld method?
thx!

**Comment by castwide** [comment]
It supports both `include` and `extend` in most cases, but the global namespace is an exception. We can make it work, though. I'll add it to the roadmap.

**Comment by castwide** [comment]
A fix for modules included in the global namespace is pushed to the castwide/solargraph master branch. It'll be published in gem v0.17.4.

**Comment by castwide** [comment]
Gem 0.17.4 is published with support for included modules in the global namespace.
