### ISSUE TITLE
autoformat in vs code deleting comments

### ISSUE THREAD

**Issue by mutantcows** [castwide/vscode-solargraph#253]
In VS Code with these settings:
```json
{
  "[ruby]": {
    "editor.defaultFormatter": "castwide.solargraph"
  },
  "solargraph.formatting": true,
}
```
This snippet:
```ruby
if var1
  # first important comment
  if var2
    # second important comment
  end
end
```
gets autoformatted to:
```ruby
if var1 && var2
  # second important comment
end
```

**Comment by castwide** [comment]
This is probably specific to RuboCop, which currently provides Solargraph's formatting capabilities. (I'm working on a plugin architecture to allow selecting other formatters.)

**Comment by mutantcows** [comment]
Opened [rubocop issue](https://github.com/rubocop/rubocop/issues/10920)
