### ISSUE TITLE
Can not read properties of undefined

### ISSUE THREAD

**Issue by baelter** [castwide/vscode-solargraph#259]
![Screenshot from 2022-09-29 11-28-56](https://user-images.githubusercontent.com/1399369/192995733-4ff79fc0-1e63-4b4e-91ab-f1a445daf874.png)

**Comment by castwide** [comment]
Confirmed. The extension doesn't account for `null` responses to `textDocument/hover`, which is a valid response according to the [specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#hover). I'll release a patch ASAP.

**Comment by castwide** [comment]
Fixed in v0.24.0.
