### ISSUE TITLE
Request textDocument/documentHighlight failed.

### ISSUE THREAD

**Issue by Abdelouadoud8** [castwide/vscode-solargraph#267]
[Error - 21:28:12] Request textDocument/documentHighlight failed.
  Message: [ArgumentError] dependency name must be a String, was nil
  Code: -32603
  
  [Error - 21:28:48] Request textDocument/hover failed.
  Message: [ArgumentError] dependency name must be a String, was nil
  Code: -32603
  
  I am getting these errors on all RoR projects even without installing solargraph on the project but only by installing the VSCode plugin,

**Comment by goutham-keywee** [comment]
@Abdelouadoud8 I ran into this error, can you explain what resolved your issue. thanks.

**Comment by yamakoud** [comment]
I ran into same error.

detailed output is below. (Two type of error was raised in my case).
```
[Error - 3:38:02 PM] Request textDocument/documentSymbol failed.
  Message: [ArgumentError] dependency name must be a String, was nil
  Code: -32603 
[Error - 3:38:02 PM] Request textDocument/documentSymbol failed.
  Message: [ArgumentError] dependency name must be a String, was nil
  Code: -32603 
[Error - 3:38:34 PM] Request textDocument/documentHighlight failed.
  Message: [ArgumentError] dependency name must be a String, 
```

**Comment by yamakoud** [comment]
In my case, it may come form conflict between ruby extensions.
Turn off some extensions and reloading window solves my problem.

FYI @goutham-keywee 
Do you still have this issue?
