### ISSUE TITLE
Logo in Visual Studio Marketplace

### ISSUE THREAD

**Issue by mydoghasfleas** [castwide/vscode-solargraph#270]
@castwide Hi Fred,

Is there any reason why the Solargraph VS Code Plugin on the VS Marketplace does not have a logo?

I guess technically there is nothing wrong with it, but aesthetically it is not very pleasing to see a plugin listing without a logo. (Almost jarring, in fact :smile: ).

Do you think you could update the Marketplace listing with your logo?

![image](https://github.com/castwide/solargraph/assets/125179869/54651b6c-3fa4-422b-a0fc-9b425383f754)

![image](https://github.com/castwide/solargraph/assets/125179869/55c490e7-8a8e-47c6-8048-3a8790dba31b)

Thanks for the great plugin, by the way!

Kind Regards,
Martin

**Comment by castwide** [comment]
Thanks for catching this. The extension has a [logo](https://github.com/castwide/vscode-solargraph/blob/master/solargraph.png), but apparently the spec for displaying it has changed. It's fixed on master and will be included in this month's release.

**Comment by castwide** [comment]
Fixed in extension v0.24.1.
