### ISSUE TITLE
string arrays as default keyword arguments throws coloring off

### ISSUE THREAD

**Issue by johrstrom** [castwide/vscode-solargraph#271]
When an array of strings is given as the default keyword argument to a function, the vscode extension here is coloring the rest of the file as a string.

1 string in the array is working fine
![image](https://github.com/castwide/solargraph/assets/4874123/d8a15148-560a-4487-93d0-b7dde9adf075)

**2 or more strings throws this off**. Now the rest of the file is colored to look like a string.  This is the unexpected behavior this ticket concerns with. 

![image](https://github.com/castwide/solargraph/assets/4874123/6f6832fd-803d-44eb-a53f-19d07e654a94)

Using `%w` for literal words works as you'd expect.

![image](https://github.com/castwide/vscode-solargraph/assets/4874123/95c6fc58-2f59-47f8-b3e9-f51050d7bffc)

(I'm not sure if this is an issue for this repository or the actual language server, but I assume you can move it as appropriate.)

I'm using version `0.24.0`.

**Comment by castwide** [comment]
This is most likely an issue with another extension or VS Code itself. The Solargraph extension does not perform coloring.

**Comment by johrstrom** [comment]
OK - Thanks for the response! I'll go ahead and close if that's the case.
