### ISSUE TITLE
Autocomplete/documentation does not work

### ISSUE THREAD

**Issue by mwoskowicz** [castwide/vscode-solargraph#28]
VSCode 1.20.1

When I type and press ctrl+space, the methods do show but there's no documentation.

![image](https://user-images.githubusercontent.com/23441349/36630184-888e8648-1962-11e8-9d70-581f2181301b.png)

I have gem installed. Should anything else be done to make this working?

**Comment by castwide** [comment]
What version of the gem are you using? This is what I get with 0.17.2:

![image](https://user-images.githubusercontent.com/3704922/36631077-a6b39f6e-193f-11e8-8a36-6451811dec2f.png)

**Comment by castwide** [comment]
I was able to reproduce this issue when I opened the file alone without opening a folder. I'll look into it.

![image](https://user-images.githubusercontent.com/3704922/36638263-289abb9c-19be-11e8-9e86-86c054f1e35d.png)

**Comment by castwide** [comment]
The problem was in the server. It didn't cache an API map for undefined workspaces, so the extension couldn't resolve details for completion items.

A fix is pushed to the castwide/solargraph master branch. It should work correctly in gem version 0.17.3.

**Comment by mwoskowicz** [comment]
Thanks @castwide 
One more thing, is it still possible to set documentation to be written inline under function name instead of in the right panel? Couldn't find such option. 
Screen as example:

**Comment by castwide** [comment]
@mwoskowicz The right panel is a feature of VS Code itself. They changed the appearance of completion items a few versions ago. That screen capture is based on VS Code from March 2017. I should update the gif in the README.

Unfortunately, I don't know of a way to change the layout. If there's a configuration setting for it, I haven't been able to find it.

**Comment by castwide** [comment]
Fix published in gem v0.17.3.
