### ISSUE TITLE
[question] Open definition in new tab

### ISSUE THREAD

**Issue by jtruzzi** [castwide/vscode-solargraph#29]
Is it possible to configure the extension to open definitions in a new tab instead of replacing the current tab? Once i go to a definition, i loose scope of the previous method i was debugging.

Peek definition is is a good replacement for that so far, but i was wondering if its possible to open a new tab to work on two files at the same time.

Thanks for the extension! 
It's super usefull!

**Comment by jtruzzi** [comment]
My bad! I see now that this is working as expected! 
I didn't notice that when the tab is not fixed (file name in cursive), it gets replaced, but if the current tab is fixed, then it opens a new tab with the definition.

Sorry!

**Comment by preejackie** [comment]
Hi, How to achieve this ? What do you mean by tab is fixed and file name is cursive? 
Thanks

**Comment by preejackie** [comment]
No problem I found out :+1:
