### ISSUE TITLE
Support renaming symbols

### ISSUE THREAD

**Issue by garyking** [castwide/vscode-solargraph#36]
Please add the ability to rename symbols in Ruby code, just like it's possible with JavaScript and Python.

Originally posted [here](https://github.com/rubyide/vscode-ruby/issues/305).

**Comment by castwide** [comment]
I've been looking into this feature as the Solargraph gem transitions to using the [language server protocol](https://github.com/Microsoft/language-server-protocol). There are already some related features that make this capability feasible. There are also a few challenges, such as how to handle ambiguous symbols. It might not make it into the first version of the language server, but it's on the roadmap.

**Comment by castwide** [comment]
The first versions of the find reference and rename symbol capabilities are scheduled for inclusion in gem version 0.22.0.

**Comment by castwide** [comment]
Published in gem 0.22.0.

**Comment by castwide** [comment]
Closing because this feature is included in the current version. If anyone encounters problems with it, please open a new issue.
