### ISSUE TITLE
Solargraph seems to handle go-to-definition/peek-definition too slow

### ISSUE THREAD

**Issue by TheTharin** [castwide/vscode-solargraph#39]
I've found some amount of similar issues here, that go-to-definition/peek-definition takes around 10-20 seconds to perform (instantaneously in Sublime Text 3), and found a solution to change it for rubyLocate. I've tried it, but have waited for almost an hour and a half for VSCode to finish Indexing Ruby source files, and nothing. It keeps indexing forever.
Is there any way to explicitly check if it's even doing anything? Or is there any way to make solargragh perform go-to-definition as fast as it's done in rubymine/sublimetext?
Code indexing in Sublime Text on my code base takes roughly 7-10 minutes. I really like the flow and looks of VS Code, but the lack of go-to-definition function makes it almost unusable.
 
If there is already a solution, I would appreciate any help! Thanks in advance!

**Comment by castwide** [comment]
Do you have the `ruby.intellisense` configuration set to `solargraph`? (There's also a configuration for `ruby.codeCompletion`.)

Do you have the latest version of the Solargraph gem? Current in v0.18.2.

Can you give me some platform specs? OS, memory/cpu?

Do you get any errors in the console (Help -> Toggle Developer Tools)? I've already caught a couple of errors that choke the server and plan to have a new gem released in a few days.

How large is your workspace? If it takes 7-10 minutes in Sublime Text, I imagine it's massive. For comparison, I typically use the core Rails project when I want to benchmark against a large codebase. About 30Kloc takes 20-30 seconds to initialize. After that, go to definition takes less than a second.

Solargraph indexes all the .rb files in your workspace by default. If there are directories that can be ignored, you can exclude them with a .solargraph.yml file. Run `solargraph config` to generate a default file. More information: http://solargraph.org/tips

**Comment by TheTharin** [comment]
Yeap, my bad. The problem was that I didn't have the gem. I've installed it, though it failed to initialize with that error: invalid byte sequence in US-ASCII

**Comment by castwide** [comment]
The invalid byte sequence error will be fixed in the next version of the gem. More information: https://github.com/castwide/solargraph/issues/33

**Comment by BobbyMcWho** [comment]
Hi, vscode doesn't  seem to like the solargraph setting for codeCompletion or intellisense: 
![image](https://user-images.githubusercontent.com/6934825/39326534-49bda9a4-4963-11e8-83eb-970fbd9df28e.png)

**Comment by castwide** [comment]
The `solargraph` option is an artifact from the version of the Ruby extension that included Solargraph as a dependency. Now that the extensions are separate again, users have the option of disabling either extension independently of the other.

The Ruby extension should treat any unrecognized value for the `codeCompletion` or `intellisense` settings as equivalent to `false`. In the case of `codeCompletion`, that would mean the Ruby extension doesn't try to use rcodetools, but the Solargraph extension should still work.

**Comment by BobbyMcWho** [comment]
Thanks @castwide , maybe my project is too large, I just can't get this extension to work reliably for the life of me unfortunately :/

**Comment by castwide** [comment]
How large is your project, insofar as number of files and lines of code?

Do you have a vendor directory? Solargraph might be trying to map it, which is typically unnecessary. See [the tips page](http://solargraph.org/tips) for information about including or excluding files in the .solargraph.yml config. In an upcoming version, vendor directories will be excluded by default.

The developer console might contain error messages. Please feel free to open new issues here or [the gem repo](https://github.com/castwide/solargraph) with any bug reports or recommendations.

**Comment by BobbyMcWho** [comment]
Thank you for the help @castwide , I can confirm that ignoring the vendor directory make things instantaneous, and the solargraph server starts right up. 👍 thank you for all the hard work.

**Comment by markeissler** [comment]
It would also make sense to ignore the `.git` directory if one exists.
