### ISSUE TITLE
html not parsed into doc completion and type not hinted for params method

### ISSUE THREAD

**Issue by didacusAbella** [castwide/vscode-solargraph#4]
When I autocomplete and the documentation is showed, the html not rendered properly
Here an example:
![schermata da 2017-06-28 14-53-47](https://user-images.githubusercontent.com/11076147/27638197-be170b5e-5c12-11e7-818b-051c579b2366.png)
As you can see there are p tags and code tags not rendered properly.
Another problem is that the extension not hint you on the type of params of a method. For example i have a ruby class in my lib directory documented as showed below:
![schermata da 2017-06-28 15-04-45](https://user-images.githubusercontent.com/11076147/27638439-8c4e2b9c-5c13-11e7-9c5c-34cb8d59b331.png)
But when I initialize the object in my main file, the documentation provided by intellisense give me no informtion about the type of the opt variable. Here a screen:
![schermata da 2017-06-28 15-05-04](https://user-images.githubusercontent.com/11076147/27638525-d814c75c-5c13-11e7-9bb6-1d45aa704f9a.png)

I hope that you will resolve this problem.
P.S Great job guys! You have created the best intellisense/autocomplete extension for ruby that i have seen so far apart RubyMine

**Comment by castwide** [comment]
Thanks!

A fix for HTML in documentation will be included in the next update.

Improved support for method params is on the roadmap, including type detection from param tags.

**Comment by didacusAbella** [comment]
Perfect. I'll wait for the updates

**Comment by castwide** [comment]
Version 0.5.0 of the extension is published. Among other things, it fixes HTML in documentation.

Method param support is still in progress.

**Comment by castwide** [comment]
Extension v0.5.1 and gem v.0.9.1 are published. If a method's documentation includes param tags, the name, type(s), and description will be listed below the summary in the completion and signature popups. Return types for arguments will also be inferred inside of methods; e.g., in the SportStructure example, referencing `opt` while inside the initialize method will recognize it as a Hash.

**Comment by didacusAbella** [comment]
Great it's awesome! The updates working but I have a problem. The doc folder and yardoc not be generated by extension anymore. I have to generate manually. It's very strange because analyzing the developer's console of VsCode when i save a ruby files the yard command is lauched as you can see in the screenshot.
![screen](https://user-images.githubusercontent.com/11076147/28821764-0d744f68-76b7-11e7-828e-a9bb915b310e.png)
 Note: the doc folder is here because I lauched it manually for try if the command was correct. Other info that I can give you is that the solargraph and yard gem are installed user-wide, the system is Archlinux and I have yet setted the absolute path of solargraph into settings of Visual Studio Code.

**Comment by castwide** [comment]
I'm looking into this, but so far I have not been able to reproduce the problem in Windows 10 or CentOS 7. It doesn't look like the yardoc command sent any errors to your developer's console, either.

Just to confirm, if you do the following:

1. Delete the .yardoc and doc folders
2. Edit and save a ruby file

Solargraph should regenerate .yardoc and doc. That's not happening?

Do you have any other processes running that might block the yardoc update, such as `yard server` or a doc page open in a browser?

**Comment by didacusAbella** [comment]
I find the problem. Is related to this [issue](https://github.com/Microsoft/vscode/issues/29412). The problem is not related to your extension. Is vscode that in my system not update the environment variables correctly if I lauch the editor from my menu. But if I lauch from command line all works properly.

**Comment by didacusAbella** [comment]
I'll close the issue because every feature has been implemented
