### ISSUE TITLE
Disable linter

### ISSUE THREAD

**Issue by RaccoonFive** [castwide/vscode-solargraph#43]
Is it possible to disable the linter? If not we should have the option to do it!

**Comment by castwide** [comment]
Set the `solargraph.diagnostics` configuration to `false`. Alternatively, you can change the linting rules with a .rubocop.yml file in your root project folder.

**Comment by RaccoonFive** [comment]
Thank you it worked! Sorry for asking here but I couldn't find the answer anywhere haha!
