### ISSUE TITLE
Default `solargraph.diagnostics` to false

### ISSUE THREAD

**Issue by jacquescrocker** [castwide/vscode-solargraph#44]
Adding solargraph to a project should not automatically enable Rubocop checking for the project. It's very difficult for people to track down:

1) where the linter is actually coming from (why would anyone expect SolarGraph?)
2) how to update the linter settings
3) how to turn it off

**Comment by jacquescrocker** [comment]
Also, the VSCode project page makes no mention of linting anywhere on it. I had to find the git repo to discover Solargraph was triggering all the green lines.

**Comment by castwide** [comment]
The project page will be updated with the repo's current README in the next release.

Default to `false` is reasonable. The configuration should probably allow for cherry-picking other capabilities as well.

**Comment by castwide** [comment]
Version 0.16.0 is published. `solargraph.diagnostics` defaults to false and the README includes documentation for diagnostics/linting.

**Comment by castwide** [comment]
This feature is liable to change. I expect configuration of diagnostics reporters to move to the .solargraph.yml file. More information: https://github.com/castwide/solargraph/issues/42

This means the `solargraph.diagnostics` configuration will probably be deprecated. The default setting will still be to disable RuboCop.

If this causes problems or anyone has other suggestions, please let me know.

**Comment by castwide** [comment]
I've decided to keep the `solargraph.diagnostics` configuration. It gives users the ability to decide whether to display diagnostics in their editor, which is a separate issue from which diagnostics rules are assigned to the project. Example: a project might use RuboCop to enforce its style guidelines, but a user should be able to opt out of notifications about it.

To that end, the `solargraph.diagnostics` options will be `true` or `false`. Default will still be `false`. Selection of reporters, including RuboCop, will still be a function of the .solargraph.yml file.

**Comment by jtokoph** [comment]
It seems like with the latest vscode and solargraph, when `"editor.formatOnSave": true` is set, this extension runs rubocop even if `"solargraph.diagnostics": false`. Is there a different way to disable solargraph diagnostics? I'm not up to speed on vscode language extensions and language servers, but I couldn't see where this setting is even being used.

**Comment by jtokoph** [comment]
Forgive the error in my previous comment. I meant to say formatting is still happening even when `"solargraph.formatting": false`

**Comment by castwide** [comment]
@jtokoph Confirmed. The server didn't take the `solargraph.formatting` setting into account when dynamically registering capabilities, so it stayed on by default. I've fixed it in the gem's master branch. The updated gem is scheduled for release by May 7.

**Comment by castwide** [comment]
Extension 0.17.0 and gem 0.21.0 fix the problem synchronizing the `solargraph.formatting` setting.

**Comment by patilarpith** [comment]
@castwide Where is the ```solargraph.diagnostics``` setting placed? Is it part of .solargraph.yml ?

**Comment by castwide** [comment]
@patilarpith It's a user/workspace preference setting in VS Code (or a value that can be sent via the `workspace/didChangeConfiguration` method with any language client).

You can use the .solargraph.yml file to select which reporters a project uses for diagnostics, e.g.:

```
reporters:
- rubocop
```

**Comment by patilarpith** [comment]
Didn't realise I was on a different repo. Followed the link from castwide/solargraph

So I've setup reporters in .solargraph.yml in the workspace root folder. Still, I'm unable to see diagnostics notification upon calling didChange. 

Is enabling diagnostics require to be done via initialization params?

**Comment by patilarpith** [comment]
That helped. Thanks

**Comment by castwide** [comment]
Default `solargraph.diagnostics` settings and updates via dynamic registration should work now. If anyone still experiences problems, please open a new issue.
