### ISSUE TITLE
Solargraph::FileNotFoundError when opening a file

### ISSUE THREAD

**Issue by theSoenke** [castwide/vscode-solargraph#46]
Every time I open a ruby file I get the following error:
```
[Error - 2:53:38 PM] Request textDocument/documentSymbol failed.
  Message: [Solargraph::FileNotFoundError] Source not found for myfile.rb
  Code: -32603 
```

I'm using the latest Solargraph version 0.19.1

**Comment by castwide** [comment]
I was able to reproduce this error by opening a Ruby file without having a workspace open in VSCode. I'll have it fixed in a gem update.

If you still get this error when you have an open workspace, please let me know.

**Comment by theSoenke** [comment]
Thanks! I've also investigated further and it seems that I'm only able to reproduce it when `explorer.openEditors.visible` is set to 0

**Comment by theSoenke** [comment]
This solved it for me. Thank you very much!
