### ISSUE TITLE
When VSCode gets the autocomplete response for Solargraph it erases the simple word autocompletion

### ISSUE THREAD

**Issue by douglascamata** [castwide/vscode-solargraph#51]
This extension have a really weird behaviour when it comes to autocompleting from the current dictionary of words (usually the active file) and from the `solargraph` gem itself.

It seems like whenever we get a response from the solargraph server with extension it automatically removes all the dictionary words from the suggestions. 

Example:

```ruby
foo

foo_string = "string"

# typing...
fo # trigger autocomplete here!
```

You won't see `foo` when you trigger the autocomplete there at the last line... you will only see `foo_string`. 😞

**Comment by castwide** [comment]
I'll have to look into this. I thought setting `editor.wordBasedSuggestions` to `true` would get suggestions from both providers, but it doesn't have any effect.

**Comment by castwide** [comment]
It looks like this is intended behavior in VSCode. Word-based suggestions don't get triggered when a provider with a higher score provides results. There's some discussion of the issue, including the possibility of an option to include both, at https://github.com/Microsoft/vscode/issues/21611.
