### ISSUE TITLE
Problem with Solargraph on Windows (ruby installed with MSYS2)

### ISSUE THREAD

**Issue by gigi206** [castwide/vscode-solargraph#55]
Hello,

I develop the tool [VSCode-Anywhere](https://github.com/gigi206/VSCode-Anywhere) and solargraph does not seem to work on Windows (few weeks ago I success).

I tried with ruby [msys2](https://www.msys2.org) :
- msys/ruby :
![msys](https://image.ibb.co/cdkbko/2.jpg)

- mingw64/mingw-w64-x86_64-ruby :
![mingw64](https://image.ibb.co/mYVyy8/3.jpg)

I also tried with [rubyinstaller](https://rubyinstaller.org/downloads/) also based on MSSY2 mingw64.
![rubyinstaller](https://image.ibb.co/kW0yy8/1.jpg)

I have the same result, I show in the status bar **solargraph is ready** but completion doesn't work and I have no error message. I have configured in user settings :
```json
{
    "solargraph.autoformat":  true,
    "solargraph.hover":  true,
    "solargraph.completion":  true,
    "solargraph.diagnostics":  true,
    "solargraph.formatting":  true
}
```

Any idea ?

**Comment by castwide** [comment]
One possible issue is that the file isn't being synchronized with the language server. Try giving it a name with an .rb extension. Changing the file's language mode to Ruby is not sufficient. (Related issue: https://github.com/castwide/vscode-solargraph/issues/34)

**Comment by gigi206** [comment]
> There's at least one edge case where it can fail: starting an untitled file before any other Ruby file has been opened, i.e., before the Solargraph extension has been activated.

Indeed it works now.

Thank you for your help.
