### ISSUE TITLE
DXRuby did not be handled autocomplite..

### ISSUE THREAD

**Issue by kemo14331** [castwide/vscode-solargraph#58]
The gem that I'm using ["dxruby"](https://rubygems.org/gems/dxruby/versions/1.4.1) didn't be handled autocomplite..
May you fix it?

Environment:
OS: Windows 10
vscode-ruby version: 0.18.0
VS Code version: 1.23.1
Ruby-Solargraph: 0.17.4
Ruby version: 2.3.3
Solargraph gem version: 0.22.0

(I'm Japanese. so my English may be strange...)

**Comment by castwide** [comment]
Try running `yard gems` to generate the documentation.

**Comment by kemo14331** [comment]
I tried running this command, but autocomplite didn't work..

**Comment by kemo14331** [comment]
I ran this command, but autocomplite didn't work..

**Comment by castwide** [comment]
I just checked the [dxruby repo](https://github.com/mirichi/dxruby). It appears to be a binary distribution. There's no source code to analyze, so there's no documentation available for it. Sorry about that.

**Comment by kemo14331** [comment]
oh..  I see.
thank you.
