### ISSUE TITLE
Failed to start language server: "Could not find command 'socket'."

### ISSUE THREAD

**Issue by athrunsun** [castwide/vscode-solargraph#59]
* OS: Linux Mint 18.3
* Desktop: Cinnamon
* VSCode version: 1.23.1
* ruby version: 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
* solargraph version: 0.17.3
* ruby & solargraph related configurations in VSCode:
```
"ruby.interpreter.commandPath": "/home/xxx/.rbenv/shims/ruby",
"ruby.pathToBundler": "/home/xxx/.rbenv/shims/bundle",
"solargraph.commandPath": "/home/xxx/.rbenv/shims/solargraph",
"solargraph.bundlerPath": "/home/xxx/.rbenv/shims/bundle",
```

Error message:
```
[Extension Host] Failed to start language server: "Could not find command \"socket\".\n"    /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:263
```

Screenshot:
![VSCode error screenshot](https://i.loli.net/2018/06/03/5b133962c7dd2.png)

What is `socket` refering to here?

I got no error when I manually start language server with `solargraph server` on the command line.

**Comment by castwide** [comment]
The latest versions of the gem and extension use the language server protocol over a socket transport instead of the old web server. I recommend upgrading to gem version 0.22.0.

**Comment by athrunsun** [comment]
@castwide Thanks for the suggestion, I upgraded solargraph gem and it works.

BTW, do I have to specify absolute path for ruby & solargraph related configurations, like `/home/xxx/.rbenv/shims/ruby`? I tried `~/.rbenv/shims/ruby` and `$HOME/.rbenv/shims/ruby` but neither of them works.

**Comment by castwide** [comment]
Yes, it should typically be an absolute path if you need to specify it.

**Comment by athrunsun** [comment]
@castwide OK, got it.
