### ISSUE TITLE
Custom port for solargraph server?

### ISSUE THREAD

**Issue by kfpo** [castwide/vscode-solargraph#6]
It would be great to have a possibility to set custom port for solargraph server in extension settings (default is 0 which could be already in use).

**Comment by castwide** [comment]
When the port is set to 0, the server selects the first available port. Typically the OS will assign something in the ephemeral range (49152 to 65535). This ensures that you don't get conflicts in case you open multiple VS Code windows. Each window runs its own server so the process can use the open workspace as its current working directory.

**Comment by kfpo** [comment]
@castwide, oh, didn't know that, sorry.
I had problem when trying to run `solargraph server -p 0`.
It was `Someone is already performing on port 0!` exception from Webrick (v 1.3.1).
I figured out, that Webrick doesn't like `localhost` in `BindAddress` option for some reason (works fine with 127.0.0.1 or 0.0.0.0). Don't know, is it just me (although I had this problem on two PCs).
Anyway, this is not extension issue.

Thank you!
