### ISSUE TITLE
Failed to start Solargraph: Could not find command "socket".

### ISSUE THREAD

**Issue by uniedcom** [castwide/vscode-solargraph#61]
I am getting the message listed above when launching my VSCode application.

Any ideas on how to get rid of it or fix the issue?

**Comment by castwide** [comment]
You probably need to update the gem. The first gem to use LSP via socket transport is 0.18.1; the current version is 0.22.0.

**Comment by uniedcom** [comment]
Your recommendation did not actually solve the problem.  It did however start me down the path of upgrading everything.  

So after upgrading Gems, my ChefDK stopped working.  I then upgraded ChefDK which fixed that.  However when I launched VScode I had a new error of solargraph Failed to start but with no other message or indication of what was wrong.

I then ran # gem install solargraph. This showed me what was missing.  The make file g++ command not found.  I then installed gcc c++ and ran the gem install solargraph command again and I no longer have any issues.

Thanks for the help.
