### ISSUE TITLE
Unable to disable symbols

### ISSUE THREAD

**Issue by jcw-** [castwide/vscode-solargraph#64]
I'd like to use both the Ruby extension (for Intellisense because the `Go to Definition` is instant, as opposed to taking 2-3 seconds with Solargraph) and the Solargraph extension (for auto-complete, for those times where I'm fine manually invoking it and waiting for the popup), but this results in both providing the same symbols to VS Code, resulting in duplication.

Is it possible to configure vscode-solargraph to stop providing symbols so that the `@` symbol lookup and new Outline feature doesn't double-up, while still serving auto-complete results?

![image](https://user-images.githubusercontent.com/6880880/41306738-53b49b20-6e34-11e8-8c41-c5fd11b0226f.png)

![image](https://user-images.githubusercontent.com/6880880/41306761-61852526-6e34-11e8-84bb-35cd3a28930d.png)

**Comment by castwide** [comment]
The definition and symbol capabilities are enabled automatically on initialization. Currently there's no way to disable them, but the protocol supports dynamic registration for both. I'll add configuration options in the next version of the extension.

**Comment by castwide** [comment]
Version 0.17.5 is published with additional configuration options.

The language server capabilities can be selected with the following boolean settings:

* `solargraph.completion`
* `solargraph.hover` (including signature help)
* `solargraph.diagnostics`
* `solargraph.autoformat`
* `solargraph.formatting`
* `solargraph.symbols`
* `solargraph.definitions`
* `solargraph.rename`
* `solargraph.references`

All the options default to `true` except `diagnostics` and `autoformat`.

Incidentally, the latest Solargraph gem includes a significant performance boost for `Go to Definition`, if you'd like to give it a try. One of its benefits is that it's capable of finding definitions in gems. You can always disable it if you prefer the vscode-ruby version. Another nice feature, changes to capability settings do not require you to restart VS Code or Solargraph; they should get picked up immediately after you save your preferences.

**Comment by castwide** [comment]
Extension version 0.17.5 adds the following boolean configuration options to let you cherry-pick which capabilities to enable:

* `solargraph.diagnostics`: Enable diagnostics reporting.
* `solargraph.completion`: Enable autocompletion.
* `solargraph.hover`: Enable tips on hover.
* `solargraph.autoformat`: Enable automatic formatting while typing.
* `solargraph.formatting`: Enable document formatting. The gem currently uses RuboCop for formatting.
* `solargraph.symbols`: Enable search for document and workspace symbols.
* `solargraph.definitions`: Enable go-to-definition.
* `solargraph.rename`: Enable symbol renaming.
* `solargraph.references`: Enable finding references.

All of the options default to `true` except `formatting`, `autoformat`, and `diagnostics`.

Incidentally, the latest gem includes improvements to go-to-definition that make it nearly instantaneous in many situations.

**Comment by castwide** [comment]
If anyone still has problems with the configuration options for capabilities, please open a new issue.
