### ISSUE TITLE
no implicit conversion of nil into String

### ISSUE THREAD

**Issue by theSoenke** [castwide/vscode-solargraph#68]
Sometimes I see the following error:
```
[Error - 4:15:44 PM] Request textDocument/hover failed.
  Message: [TypeError] no implicit conversion of nil into String
  Code: -32603 
```

I have only seen this when editing specs. Shouldn't solargraph also by default ignore files in `spec/`?

**Comment by castwide** [comment]
Solargraph still processes excluded Ruby files when you open them in an editor. The exclusion rule prohibits them from being mapped as part of the workspace. For example, a class defined in a `spec` file should not be visible from a `lib` file.

That error probably occurs when you move the cursor over a particular word. Any chance you can identify the location and post the relevant code?

**Comment by theSoenke** [comment]
Thanks for your response. I will try to reproduce this and post an example if find something

**Comment by castwide** [comment]
Gem version 0.25.1 includes a change that should fix this issue. More information: castwide/solargraph#82
