### ISSUE TITLE
[Feature-Request] add completion for hook methods

### ISSUE THREAD

**Issue by didacusAbella** [castwide/vscode-solargraph#7]
it is a common practice for ruby programmers to add methods dynamically when some modules are extended, prepended  or included. For example:
```ruby
module MyModule
  def self.included(klass)
    klass.class_eval do
     # This method add new functionality
     # @param an_argument [SomeType] a specific argument
     # @return [SomeType]
     def another_method(an_argument)
       #Some business code
     end
   end
 end
end

class MyClass
  include MyModule
end

kl = MyClass.new
kl. # => it would be great if in method suggestion appears another_method too
```
the same functionality would be great for the other ruby hook methods and for `klass.instance_eval` method

**Comment by castwide** [comment]
Detecting dynamic methods is tricky. I might be able to make it work in limited cases, but there will always be exceptions. The only 100% reliable solution is to execute the code, which Solargraph intentionally avoids doing.

One alternative is to use YARD directives. Example using the @!method directive:

    module MyModule
      # @!method another_method(an_argument)
      #   This method add new functionality
      #   @param an_argument [SomeType] a specific argument
      #   @return [SomeType]

      def self.included(klass)
        klass.class_eval do
          def another_method(an_argument)
            #Some business code
          end
        end
      end
    end

    class MyClass
      include MyModule
    end

    kl = MyClass.new
    kl. # => another_method appears in suggestions

Note: suggestions from YARD directives will only be available if the file is included in the generated .yardoc directory. By default, YARD only reads the workspace's lib and app directories. That setting can be changed with a .yardopts file. A future version of the Solargraph gem might be able to parse directives locally.

I'm open to other suggestions for improving detection of dynamic methods. It's a hard problem.

**Comment by castwide** [comment]
As of gem version 0.15.0, there are two additions that can help with this feature:

* Improved macro support. Any `@!method` and `@!attribute` macros in your workspace get mapped into completion suggestions. A local yardoc is not required.

* The experimental `Runtime` plugin. Solargraph can run a subprocess that queries your project's classes and modules for "magic" methods. More information is available in the [Solargraph README](https://github.com/castwide/solargraph).

**Comment by didacusAbella** [comment]
Very Nice!! I'll try it as soon as possible
