### ISSUE TITLE
Report of excessive battery usage

### ISSUE THREAD

**Issue by Tyriar** [castwide/vscode-solargraph#71]
FYI https://github.com/Microsoft/vscode/issues/53985#issuecomment-406316551

**Comment by castwide** [comment]
There's an issue discussing improvements to CPU performance in the Solargraph gem at https://github.com/castwide/solargraph/issues/81.

**Comment by castwide** [comment]
Please refer to castwide/solargraph#81 for ongoing discussion of battery/CPU issues.
