### ISSUE TITLE
Failed to start Solargraph: 

### ISSUE THREAD

**Issue by LewisAndrewCampbell** [castwide/vscode-solargraph#72]
Solar graph seems to be installed and running, but I still get the message when starting vscode. Any clues?

$ irb
irb(main):001:0> require 'solargraph'
=> true

$ solargraph
Commands:
  solargraph --version, -v                           # Print the version
  solargraph available-cores                         # List available documentation versions
  solargraph clear-cores                             # Clear the cached core documentation
  solargraph config [DIRECTORY]                      # Create or overwrite a default configuration file
  solargraph download-core [VERSION]                 # Download core documentation
  solargraph help [COMMAND]                          # Describe available commands or one specific command
  solargraph list-cores                              # List the local documentation versions
  solargraph reporters                               # Get a list of diagnostics reporters
  solargraph socket                                  # Run a Solargraph socket server
  solargraph stdio                                   # Run a Solargraph stdio server
  solargraph suggest c, col, --column=N l, --line=N  # Get code suggestions for the provided input

**Comment by castwide** [comment]
What OS are you using?

I assume the error appears in a window message like this one:

![image](https://user-images.githubusercontent.com/3704922/43799392-67fbc678-9a5b-11e8-825c-1c266ac9a82f.png)

Is there any more information available when you expand the message, or are there any error messages in the developer console (Help -> Toggle Developer Tools)?

**Comment by LewisAndrewCampbell** [comment]
FWIW I get the message:

Failed to start language server: "/bin/bash: solargraph: command not found

But I think actually this is an issue on my end, for some reason starting vscode with dmenu_run (on linux x64) I get that message, but when I start it from a terminal the extension works fine.

I'll close it off, thanks for responding.
