### ISSUE TITLE
No definitions found for variable

### ISSUE THREAD

**Issue by mjnorman** [castwide/vscode-solargraph#75]
Hello!  Let me start by saying I'm new to Ruby and using an existing project to modify/learn as I go.  The extension seems to work great for system libraries and classes.  However when I goto/peek definition for an exposed variable (@variablename) there is no definition found.  In this example the variable is defined two folder levels up in the project.  No errors are present in the dev log in vscode.  Is this functionality supposed to work or is there something I'm doing wrong?

```
[Extension Host] Solargraph is listening PORT=52056 PID=16976

 [Extension Host] Checking gem version
 [Extension Host] Solargraph gem version is current
```
Solargraph: 0.26.1
vscode: 1.26.1
gem: 2.6.14.1
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]

Windows 10x64

Any help appreciated, thanks for the great extension!

edit: sorry I linked you user @.whatever :)

**Comment by castwide** [comment]
Goto/peek should take you to the variable's assignment if it's visible in the current context. For instance variables, that means you have to be in the same scope (either class or instance).

```Ruby
class Example
  def instance_method
    @instance_variable ||= 'my variable' # The assignment is in an instance method
  end
end

# ...

class Example
  def another_method
    @instance_variable # This is an instance method. You can goto/peek the assignment
  end

  @instance_variable # This is the class scope. Goto/peek will not work
end

@instance_variable # This is outside the Example namespace. Goto/peek will not work
```

**Comment by mjnorman** [comment]
Thanks for the reply.  I confirmed this works if I got into the class definition and peek it from there.  Is this the same case for inheritance?  Specifically I am looking at the java_buildpack for cloud foundry, which I have a fork of [here](https://github.com/mjnorman/java-buildpack).

snippet below, removing comments/extra variables for brevity--
```
#  ./component/base_component.rb

    class BaseComponent
      include JavaBuildpack::Util::Shell

      def initialize(context)
        @droplet        = context[:droplet]       #<------ this is the variable I'm interested in.
      end
...
```

```
#  ./component/versioned_dependency_component.rb

    class VersionedDependencyComponent < BaseComponent   #<-----  inherited
...
```

```
#  ./container/tomcat/tomcat_instance.rb

    class TomcatInstance < JavaBuildpack::Component::VersionedDependencyComponent  #<---- inherited 
...
      def compile
        ...
        @droplet.additional_libraries << tomcat_datasource_jar if tomcat_datasource_jar.exist?  #<---- peek/goto does not work here, should it?
        ...
      end

**Comment by mjnorman** [comment]
Also not to muddy the issue, but when clicking the object within the peek window, vscode opens another window, and I see "Loading.."  Error in the console is below:

```ERR [ArgumentError] Invalid namespace object: JavaBuildpack::BuildpackVersion#hash: Error: [ArgumentError] Invalid namespace object: JavaBuildpack::BuildpackVersion#hash
	at new ResponseError (C:\Users\mnorma001.CABLE\.vscode\extensions\castwide.solargraph-0.17.6\node_modules\vscode-jsonrpc\lib\messages.js:46:28)
	at handleResponse (C:\Users\mnorma001.CABLE\.vscode\extensions\castwide.solargraph-0.17.6\node_modules\vscode-jsonrpc\lib\main.js:430:48)
	at processMessageQueue (C:\Users\mnorma001.CABLE\.vscode\extensions\castwide.solargraph-0.17.6\node_modules\vscode-jsonrpc\lib\main.js:258:17)
	at Immediate._onImmediate (C:\Users\mnorma001.CABLE\.vscode\extensions\castwide.solargraph-0.17.6\node_modules\vscode-jsonrpc\lib\main.js:242:13)
	at runCallback (timers.js:789:20)
	at tryOnImmediate (timers.js:751:5)
	at processImmediate [as _immediateCallback] (timers.js:722:5)```

**Comment by castwide** [comment]
Solargraph currently does not detect instance variables from superclasses, but it probably should. I'll add it to the roadmap.

That link you clicked should open a documentation page with additional information about the object. It looks you found a bug in the process that generates the documentation. I'll check into that as well.

**Comment by castwide** [comment]
The next release of the gem will include detection of superclass instance variables and fix the above document page bug.

**Comment by castwide** [comment]
Gem 0.27.0 is released with superclass instance variable detection.
