### ISSUE TITLE
Can't install solargraph gem

### ISSUE THREAD

**Issue by sluny** [castwide/vscode-solargraph#76]
<img width="505" alt="screen shot 2018-09-10 at 6 24 50 pm" src="https://user-images.githubusercontent.com/42814373/45327761-d57e2980-b526-11e8-9e92-55a43c36063d.png">

Shachars-MacBook-Pro:cmsc330fall18 ShacharLuny$ gem install solargraph
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.3.0 directory.
Shachars-MacBook-Pro:cmsc330fall18 ShacharLuny$

**Comment by castwide** [comment]
It looks like you're trying to install the gem to a system-level installation of Ruby and your user account doesn't have the proper permissions. If that's the case, you should see the same error with any other gem you try to install.

A couple links that might help:

http://help.rubygems.org/discussions/problems/26283-gems-broken-on-mac-os-x-sierra

https://stackoverflow.com/questions/18599889/error-while-executing-gem-gemfilepermissionerror
