### ISSUE TITLE
Fail to Building native extensions. on Mac OSX 10.13.6

### ISSUE THREAD

**Issue by fascox** [castwide/vscode-solargraph#78]
Building native extensions.  This could take a while...
ERROR:  Error installing solargraph:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7/ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20180912-38268-nmeu8e.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/eventmachine-1.2.7 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-17/2.3.0/eventmachine-1.2.7/gem_make.out

**Comment by castwide** [comment]
It looks like you don't have the Ruby development headers installed. The easiest way I know to get them on OSX is to install XCode.

Relevant links:

https://stackoverflow.com/questions/761521/when-i-try-sudo-gem-install-json-i-get-the-following-error

https://kevinpotgieter.wordpress.com/2012/12/06/ruby-gem-install-mkmf-rb-cant-find-header-files-for-ruby-problem/

**Comment by fascox** [comment]
`xcode-select --install`

and 

`sudo xcodebuild -license`

solve the issue.

**Comment by acalism** [comment]
> `xcode-select --install`
> 
> and
> 
> `sudo xcodebuild -license`
> 
> solve the issue.

restart macOS is required for me.

**Comment by xclidongbo** [comment]
macos 10.14.6.
same error.

**Comment by naffan2014** [comment]
same error

**Comment by Calebvh** [comment]
Same error, (trying to install Jazzy)
current directory: /Library/Ruby/Gems/2.3.0/gems/redcarpet-3.5.0/ext/redcarpet
xcode-select --install
and
sudo xcodebuild -license
and then subsequent restart have not worked, any suggestions?

**Comment by castwide** [comment]
You might need to install the command line tools: https://kevinpotgieter.wordpress.com/2012/12/06/ruby-gem-install-mkmf-rb-cant-find-header-files-for-ruby-problem/

**Comment by Calebvh** [comment]
Unfortunately I already have them installed, any other ideas?

**Comment by castwide** [comment]
This might be specific to MacOS 10.14. Apparently some development files got moved, or stopped getting installed by default, or...something. A couple of people have recommended running some variation of this:

```
open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
```

References:
* https://blog.driftingruby.com/updated-to-mojave/
* https://desiredpersona.com/install-jekyll-on-macos/
* https://stackoverflow.com/questions/46377667/docker-for-mac-mkmf-rb-cant-find-header-files-for-ruby

**Comment by Calebvh** [comment]
Yes, I was just about to post. 
navigating to that package location and then entering:
sudo installer -pkg macOS_SDK_headers_for_macOS_10.14.pkg -target / 
This did the trick for me, thanks for your help!

**Comment by jasonivers** [comment]
Installing the package fixed that problem for me, but it's not picking up my RVM ruby version when I do bundle install now... even though ruby --version DOES display it.  Any ideas?

**Comment by jkuebart** [comment]
The cause is that Xcode 11 ships the macOS 10.15 SDK which includes headers for ruby2.6, but not for macOS 10.14's ruby2.3. You can verify that this is your problem by running

    ruby -rrbconfig -e 'puts RbConfig::CONFIG["rubyhdrdir"]'   

which on macOS 10.14 with Xcode 11 prints the **non-existent** path

    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0

There might still be a macOS 10.14 SDK in `/Library/Developer/CommandLineTools/SDKs`. It isn't necessary to pollute the system directories by installing the old header files as suggested above. Instead, by pointing the `SDKROOT` environment variable to it, the appropriate ruby2.3 headers will be found:

    SDKROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/
    export SDKROOT
    ruby -rrbconfig -e 'puts RbConfig::CONFIG["rubyhdrdir"]'

This should now correctly print

    /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk//System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/include/ruby-2.3.0

Likewise, `gem install` should work when the `SDKROOT` environment variable is set.

**Comment by mackworth** [comment]
For me (Xcode 11 on Mojave as well), `gem install` didn't seem to use the SDKROOT, even though RBConfig returned the right value.  This suggestion on StackOverflow worked instead, so I'm passing it on here:

`sudo xcode-select --switch /Library/Developer/CommandLineTools`
and then restore afterwards with 
`sudo xcode-select --switch /Applications/Xcode.app`

Reference: https://stackoverflow.com/a/58231417/580850

**Comment by ccarpita** [comment]
If you are on OSX 10.15+, the headers package is no longer available. I fixed this issue by setting `SDKROOT` in my shell configuration, which should be mostly future-proof:

```
export SDKROOT=$(xcrun --show-sdk-path)
```

**Comment by boxabirds** [comment]
> This might be specific to MacOS 10.14. Apparently some development files got moved, or stopped getting installed by default, or...something. A couple of people have recommended running some variation of this:
> 
> ```
> open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
> ```
> 
> References:
> 
> * https://blog.driftingruby.com/updated-to-mojave/
> * https://desiredpersona.com/install-jekyll-on-macos/
> * https://stackoverflow.com/questions/46377667/docker-for-mac-mkmf-rb-cant-find-header-files-for-ruby

Thanks! I'm on 10.14.4 and this was still necessary.

**Comment by s18692001** [comment]
> For me (Xcode 11 on Mojave as well), `gem install` didn't seem to use the SDKROOT, even though RBConfig returned the right value. This suggestion on StackOverflow worked instead, so I'm passing it on here:
> 
> `sudo xcode-select --switch /Library/Developer/CommandLineTools`
> and then restore afterwards with
> `sudo xcode-select --switch /Applications/Xcode.app`
> 
> Reference: https://stackoverflow.com/a/58231417/580850

Thank you sir!

**Comment by mineschan** [comment]
> If you are on OSX 10.15+, the headers package is no longer available. I fixed this issue by setting `SDKROOT` in my shell configuration to the value provided by `xcrun`, which should be mostly future-proof:
> 
> ```
> export SDKROOT=$(xcrun --show-sdk-path)
> ```

Only this solve my issue! Salute Sir!

**Comment by nomasprime** [comment]
Nothing worked for me on 10.15.7.

**Comment by philippfrank** [comment]
None of the above worked on `10.15.7` (Catalina). However, I got it up and running using `rbenv`:

```
rbenv global 2.7.4
gem install solargraph
```

**Comment by castwide** [comment]
Ruby on MacOS is frequently problematic, especially if you're using whatever janky version of Ruby ships with the OS, which often does not include the stuff you need to natively compile depenencies like Nokogiri. The problems are not limited to Solargraph. One common solution is to use rbenv, which Solargraph makes an effort to support.
