### ISSUE TITLE
Duplication in hover popups

### ISSUE THREAD

**Issue by gottlike** [castwide/vscode-solargraph#79]
When hovering over something, the documentation is oftentimes duplicated inside the popup window:

![screen](https://user-images.githubusercontent.com/278766/45537670-2b8fed00-b805-11e8-8677-677f9f0595c5.png)

While typing, it's fine though:

![screen2](https://user-images.githubusercontent.com/278766/45537707-46faf800-b805-11e8-8579-4448e5cc9485.png)

**Comment by castwide** [comment]
Reproduced with gem v0.27.1. The server is duplicating definitions when the gem is referenced in multiple `require`s. It should be fixed in gem v.0.28.0.

**Comment by castwide** [comment]
The fix is published in gem v.0.28.0.

**Comment by gottlike** [comment]
It's alright now - thanks for the quick fix!
