### ISSUE TITLE
Failing to find Solargraph gem with Fish Shell installed

### ISSUE THREAD

**Issue by richjdsmith** [castwide/vscode-solargraph#85]
Using VSCode Version 1.29, on macOS 10.12.6 and have Solargraph listed in Gem List (`solargraph (0.28.4, 0.28.3, 0.28.2, 0.28.1, 0.28.0, 0.26.1, 0.24.1, 0.23.5, 0.23.3, 0.23.2, 0.22.0)`)

The only thing that changed is I installed the Fish Shell yesterday.

**Comment by richjdsmith** [comment]
Running `$solargraph -v` on the VSCode integrated shell results in `0.28.4`

**Comment by richjdsmith** [comment]
Tried to add the result from `which solargraph` to my `solargraph.commandPath` as `/Users/richsmith/.rvm/gems/ruby-2.5.1/bin/solargraph`

Closed and reponed VScode, result is now a simple error message of `Failed to start Solargraph: ` with an empty result

**Comment by richjdsmith** [comment]
Checked developer tools. Turns out Fish Shell breaks everything ruby related 😕

Not this plugins fault or issue. Closing this issue as it is not relevant.

**Comment by jcat4** [comment]
Just wanted to say, in case anyone else wants to start playing with ruby but does **_NOT_** want to give up their precious fish shell 😍, my solution was:

(I'm on a Mac)
- Change your system shell to bash by running `chsh -s /bin/bash`
- Change your terminal application to open with fish (for example, in the vanilla terminal app in Mac OS, go to Terminal -> Preferences, and under the General tab, check the "**Command**" bubble for the "**Shells open with:**" setting, and set it to the path where your fish bin is (you can find this with `which fish`))
- In VS Code, go to Preferences -> Settings, search for "Shell", and under the **Integrated > Shell** pieces, find your OS (for Mac, **Terminal > Integrated > Shell: Osx**), and enter the path to your fish bin (again, can find with `which fish`)

Logout and log back in, and it should all work!

P.S. I believe there's a command you can use to get stuff working _without_ a logout/restart, but I can't remember it. :^)
