### ISSUE TITLE
New release soon?

### ISSUE THREAD

**Issue by ianks** [castwide/vscode-solargraph#86]
This extension does not not properly detect bundler for my setup (arch linux, rbenv, zsh). However, when runing the github version i cloned, things worked. i'm not sure why exactly, but i was happy :)

Are you planning to post an update soon or should I compile and install a local version?

**Comment by castwide** [comment]
Glad to hear the github version worked. There have been ongoing issues with zsh, and I was hoping this update would resolve them (or most of them, at least).

I expect to release version 0.18.0 this week.

**Comment by castwide** [comment]
Version 0.18.0 is published.
