### ISSUE TITLE
Unable to restart language server

### ISSUE THREAD

**Issue by wldyslw** [castwide/vscode-solargraph#89]
Hi, first of all, thank you a lot for a such useful extension!

My system:

* OS: Ubuntu 18.04.1
* ruby: 2.5.3 (set by rbenv)
* solargraph gem: 0.29.4
* vscode: 1.29.1
* Ruby Solargraph: 0.18.0

On the **very first** launch of VS Code in current user session, extension starts normally as it should be. But if I'm trying to restart server via `ctrl + shift + p` -> `Solargraph: Restart Solargraph`, or by reloading VS Code itself, server does not start, constantly notifying me in editor's status bar *"Starting the Solargraph language server..."*.

*Output* panel says literally nothing. The only interesting thing is that every try of restarting language server causes launching of process with command `/usr/bin/zsh -i -c solargraph socket --port 0` which i guess supposed to be `/usr/bin/zsh -i -c 'solargraph socket --port 0'` (notice quotes) for correct launching.

**Comment by jezman** [comment]
- OS: Ubuntu 18.10
- ruby: 2.5.1 (set by rvm)
- solargraph gem: 0.29.4
- vscode: 1.29.1

Same problem... Gem downgrading doesn't help.

**Comment by wldyslw** [comment]
> Gem downgrading doesn't help.

Just for me, downgrading extension to `0.17.6` fortunately solves this issue

**Comment by welkie** [comment]
I am not able to reproduce this. When I start VS Code from scratch, reload the window, or reload the extension, it always goes from `Starting the Solargraph language server...` to `Solargraph is ready.` quickly. I use Ubuntu 18.10 with rbenv.

```
~ > which rbenv
/home/matt/.rbenv/bin/rbenv
~ > rbenv -v
rbenv 1.1.1-39-g59785f6
~ > which ruby
/home/matt/.rbenv/shims/ruby
~ > ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
~ > which solargraph
/home/matt/.rbenv/shims/solargraph
~ > solargraph -v
0.29.4
~ > code -v
1.29.1
bc24f98b5f70467bc689abf41cc5550ca637088e
x64
```

**Comment by wldyslw** [comment]
I've realized that the problem is definitely with my default shell which is zsh. Setting bash as default shell solves problem with extension.

**Comment by castwide** [comment]
Thanks to everyone for all the feedback on this issue. I think @wldyslw is on the right track with how the server process gets launched from zsh. I have a possible solution; if it works, I'll report here and publish it in a patch release.

**Comment by castwide** [comment]
The most recent extension (vscode-solargraph 0.19.0) and gem (solargraph 0.30.0) should resolve this issue. Tested with zsh on MacOS.

**Comment by wldyslw** [comment]
I've tried it out, and looks like everything is working now. Thank you a lot for investigating this issue!

**Comment by droznyk** [comment]
I have the same problem for two weeks. I'm using asdf instead of rbenv.
```
 ~  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
 ~  which asdf    
/home/patryk/.asdf/bin/asdf
 ~  asdf --version
v0.6.1
 ~  which ruby
/home/patryk/.asdf/shims/ruby
 ~  ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
 ~  which solargraph
/home/patryk/.asdf/shims/solargraph
 ~  solargraph -v
0.31.0
 ~  code -v
1.30.2
61122f88f0bf01e2ac16bdb9e1bc4571755f5bd8
x64
 ~  echo $0
/usr/bin/zsh

```

**Comment by castwide** [comment]
@droznyk I'm not familiar with asdf, so I can't suggest anything to troubleshoot it specifically.

One thing you can try is setting the extension's `solargraph.commandPath` setting to the path you got from `which solargraph`.

**Comment by jemminger** [comment]
I'm on 0.19.1, macOS 10.14.2, and on some of my larger Rails projects the status bar never progresses past "Starting the solargraph language server..."

**Comment by castwide** [comment]
@jemminger How large are the projects? e.g., number of files, approx. lines of code, and number of gems.

Do you get any errors in the developer console (Help -> Toggle Developer Tools)?

Improving load times for large projects is an ongoing concern. For comparison, the `castwide/solargraph` repo takes about 20 seconds to initialize in VS Code, and `rails/rails` takes about 2 minutes.

**Comment by jemminger** [comment]
@castwide Interesting, the console showed that the gem wasn't installed despite the extension being installed.  I think this happened because I recently blew away my RVM install and started over.

I manually installed solargraph now and it initialized as expected in about 20 seconds.  

May be a bug that I wasn't prompted to install the gem?

**Comment by castwide** [comment]
Yes, that's a bug. The extension should notify you when the gem isn't installed and/or it couldn't start the server. Related: #100

**Comment by hughevans** [comment]
https://github.com/castwide/vscode-solargraph/issues/89#issuecomment-454691848

After ~6 months of trying on and off to get Solargraph in VS Code to work this actually fixed it for me. Admittedly I never tried very hard and I’m now very happy that it’s working, but I think this is probably a pretty prevalent issue.

**Comment by chaffeqa** [comment]
https://github.com/castwide/vscode-solargraph/issues/89#issuecomment-454691848

I agree, ☝️ that comment held the key for me, i use [asdf](https://github.com/asdf-vm/asdf) and AFAIK there are x2 options:

1. you can add `gem solargraph, group: [:development]` to your `Gemfile` in the working project, and then check the `Solargraph: Use Bundler` option in `Settings` VScode view (to make sure it uses `bundle exec` or it will not find it)
2. you can install the gem locally (make sure you are on the correct `RVM`, `rubyenv`, `asdf` gemset/ruby version/shim, and run `gem install solargraph`, then run `which solargraph`, copy that output, and put it into the `Solargraph: Command Path`  in `Settings` VScode view
