### ISSUE TITLE
Debugging support?

### ISSUE THREAD

**Issue by welkie** [castwide/vscode-solargraph#90]
I was wondering if there are plans to add debugging support to this extension.

There's another VS Code extension for Ruby (https://github.com/rubyide/vscode-ruby) that supports debugging but I prefer the code completion and refactoring features provided by Solargraph. They have plans to add features to their language server (https://github.com/rubyide/vscode-ruby/issues/317) but their plans appear to lag behind the features this language server already has.

One thing I thought of was installing both extensions and trying to disable the other extension's features except for the debugging support, so that I could combine them, but I'm afraid of any side effects that might occur.

**Comment by castwide** [comment]
Currently there are no plans to incorporate debugging into vscode-solargraph. The good news, however, is that this extension and  vscode-ruby should play well together. The overlapping features should be disabled in vscode-ruby by default. I use both extensions and haven't encountered any problems.

**Comment by welkie** [comment]
That's good to hear. Is there cooperation between you and the vscode-ruby dev? Can we count on all the non-debugging features always being disabled by default in vscode-ruby?

**Comment by welkie** [comment]
Great! Thanks for spending that effort to cooperate with them. I'll install both extensions.
