### ISSUE TITLE
Show Progress Indicator while server is loading

### ISSUE THREAD

**Issue by electr0sheep** [castwide/vscode-solargraph#97]
The language server takes quite a while to load for me (I'm working in quite a big rails project). It would be nice if the server could be started more quickly, however, if we could at least get a progress indicator, I'd know that something was happening.

(On a completely unrelated note, solargraph is phenomenal, thanks a lot for the work you've put into it.)

**Comment by castwide** [comment]
Extension 0.19.3 includes the spinner from #98. A progress tracker that reports percent complete is still a possibility for a future version.
